// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: audio.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Audio : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoContract()]
        public partial class SettingsDocument : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"output_setup")]
            public Audio.OutputSetup OutputSetup { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"monitor_device")]
            public Audio.Device MonitorDevice { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"monitor_on_mains")]
            public bool MonitorOnMains { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class OutputSetup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
            public Uuid Uuid { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"audio_device")]
            public Audio.Device AudioDevice { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"logical_channels")]
            public global::System.Collections.Generic.List<Audio.LogicalChannel> LogicalChannels { get; } = new global::System.Collections.Generic.List<Audio.LogicalChannel>();

            [global::ProtoBuf.ProtoMember(4, Name = @"audio_delay")]
            public double AudioDelay { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"master_level")]
            public double MasterLevel { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"physical_chanels")]
            public global::System.Collections.Generic.List<Audio.PhysicalChannel> PhysicalChanels { get; } = new global::System.Collections.Generic.List<Audio.PhysicalChannel>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Device : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue("")]
            public string renderID { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"input_channel_count")]
            public uint InputChannelCount { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"output_channel_count")]
            public uint OutputChannelCount { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"formats")]
            public global::System.Collections.Generic.List<Format> Formats { get; } = new global::System.Collections.Generic.List<Format>();

            [global::ProtoBuf.ProtoContract()]
            public partial class Format : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"sample_rate")]
                public uint SampleRate { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"bit_depth")]
                public uint BitDepth { get; set; }

                [global::ProtoBuf.ProtoMember(3)]
                public Type type { get; set; }

                [global::ProtoBuf.ProtoContract()]
                public enum Type
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_INT")]
                    TypeInt = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_FLOAT")]
                    TypeFloat = 1,
                }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class LogicalChannel : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
            public Uuid Uuid { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"index")]
            public uint Index { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"muted")]
            public bool Muted { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"physical_audio_channels")]
            public global::System.Collections.Generic.List<OutputChannel> PhysicalAudioChannels { get; } = new global::System.Collections.Generic.List<OutputChannel>();

            [global::ProtoBuf.ProtoMember(6, Name = @"solo")]
            public bool Solo { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"test_tone")]
            public bool TestTone { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class OutputChannel : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"index")]
                public uint Index { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"muted")]
                public bool Muted { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"solo")]
                public bool Solo { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"test_tone")]
                public bool TestTone { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class PhysicalChannel : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"index")]
            public uint Index { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"mute_enable")]
            public bool MuteEnable { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"solo_enable")]
            public bool SoloEnable { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"tone_enable")]
            public bool ToneEnable { get; set; }

        }

    }

}


#endregion
