// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: background.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Background : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"is_enabled")]
        public bool IsEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"color")]
        public Color Color
        {
            get => __pbn__Fill.Is(1) ? ((Color)__pbn__Fill.Object) : default;
            set => __pbn__Fill = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeColor() => __pbn__Fill.Is(1);
        public void ResetColor() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Fill, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__Fill;

        [global::ProtoBuf.ProtoMember(2, Name = @"gradient")]
        public Graphics.Gradient Gradient
        {
            get => __pbn__Fill.Is(2) ? ((Graphics.Gradient)__pbn__Fill.Object) : default;
            set => __pbn__Fill = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeGradient() => __pbn__Fill.Is(2);
        public void ResetGradient() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Fill, 2);

    }

}


#endregion
