// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: baseDocument.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Document : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"application_info")]
        public ApplicationInfo ApplicationInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"uses_relative_urls")]
        public bool UsesRelativeUrls { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"workspace")]
        public Workspace Workspace { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CacheInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"application_version")]
        public Version ApplicationVersion { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"url")]
        public Url Url { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"last_modified_date")]
        public double LastModifiedDate { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PVPDocumentState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"primary_playlist")]
        public PlaylistState PrimaryPlaylist { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"alternate_playlist")]
        public PlaylistState AlternatePlaylist { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"playlist_split_is_vertical")]
        public bool PlaylistSplitIsVertical { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"targeted_layer")]
        public Uuid TargetedLayer { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"selected_layer")]
        public Uuid SelectedLayer { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"locked_layer")]
        public Uuid LockedLayer { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"live_video_playlist_scale")]
        public double LiveVideoPlaylistScale { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"split_view_divider_position")]
        public double SplitViewDividerPosition { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class PlaylistState : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(2, Name = @"uuid")]
            public Uuid Uuid { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"layout")]
            public LayoutType Layout { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"item_scale")]
            public double ItemScale { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum LayoutType
            {
                [global::ProtoBuf.ProtoEnum(Name = @"LAYOUT_TYPE_CUE")]
                LayoutTypeCue = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"LAYOUT_TYPE_ACTION")]
                LayoutTypeAction = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"LAYOUT_TYPE_LIVE_VIDEO")]
                LayoutTypeLiveVideo = 2,
            }

        }

    }

}


#endregion
