// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: basicTypes.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract(Name = @"URL")]
    public partial class Url : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3)]
        public Platform platform { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"absolute_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AbsoluteString
        {
            get => __pbn__Storage.Is(1) ? ((string)__pbn__Storage.Object) : "";
            set => __pbn__Storage = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeAbsoluteString() => __pbn__Storage.Is(1);
        public void ResetAbsoluteString() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Storage, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__Storage;

        [global::ProtoBuf.ProtoMember(2, Name = @"relative_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RelativePath
        {
            get => __pbn__Storage.Is(2) ? ((string)__pbn__Storage.Object) : "";
            set => __pbn__Storage = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeRelativePath() => __pbn__Storage.Is(2);
        public void ResetRelativePath() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Storage, 2);

        [global::ProtoBuf.ProtoMember(4, Name = @"local")]
        public LocalRelativePath Local
        {
            get => __pbn__RelativeFilePath.Is(4) ? ((LocalRelativePath)__pbn__RelativeFilePath.Object) : default;
            set => __pbn__RelativeFilePath = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeLocal() => __pbn__RelativeFilePath.Is(4);
        public void ResetLocal() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__RelativeFilePath, 4);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__RelativeFilePath;

        [global::ProtoBuf.ProtoMember(5, Name = @"external")]
        public ExternalRelativePath External
        {
            get => __pbn__RelativeFilePath.Is(5) ? ((ExternalRelativePath)__pbn__RelativeFilePath.Object) : default;
            set => __pbn__RelativeFilePath = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeExternal() => __pbn__RelativeFilePath.Is(5);
        public void ResetExternal() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__RelativeFilePath, 5);

        [global::ProtoBuf.ProtoContract()]
        public partial class LocalRelativePath : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public Root root { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"path")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Path { get; set; } = "";

            [global::ProtoBuf.ProtoContract()]
            public enum Root
            {
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_UNKNOWN")]
                RootUnknown = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_BOOT_VOLUME")]
                RootBootVolume = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_USER_HOME")]
                RootUserHome = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_USER_DOCUMENTS")]
                RootUserDocuments = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_USER_DOWNLOADS")]
                RootUserDownloads = 4,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_USER_MUSIC")]
                RootUserMusic = 5,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_USER_PICTURES")]
                RootUserPictures = 6,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_USER_VIDEOS")]
                RootUserVideos = 7,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_USER_DESKTOP")]
                RootUserDesktop = 11,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_USER_APP_SUPPORT")]
                RootUserAppSupport = 8,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_SHARED")]
                RootShared = 9,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_SHOW")]
                RootShow = 10,
                [global::ProtoBuf.ProtoEnum(Name = @"ROOT_CURRENT_RESOURCE")]
                RootCurrentResource = 12,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ExternalRelativePath : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"macos")]
            public MacOSExternalVolume Macos { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"win32")]
            public Win32ExternalVolume Win32 { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"path")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Path { get; set; } = "";

            [global::ProtoBuf.ProtoContract()]
            public partial class MacOSExternalVolume : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"volume_name")]
                [global::System.ComponentModel.DefaultValue("")]
                public string VolumeName { get; set; } = "";

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Win32ExternalVolume : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"drive_letter")]
                [global::System.ComponentModel.DefaultValue("")]
                public string DriveLetter { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2, Name = @"volume_name")]
                [global::System.ComponentModel.DefaultValue("")]
                public string VolumeName { get; set; } = "";

                [global::ProtoBuf.ProtoMember(3, Name = @"network_share")]
                public bool NetworkShare { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Platform
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_UNKNOWN")]
            PlatformUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_MACOS")]
            PlatformMacos = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_WIN32")]
            PlatformWin32 = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_WEB")]
            PlatformWeb = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class URLs : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"urls")]
        public global::System.Collections.Generic.List<Url> Urls { get; } = new global::System.Collections.Generic.List<Url>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"UUID")]
    public partial class Uuid : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string String { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IntRange : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start")]
        public int Start { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"end")]
        public int End { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Color : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"red")]
        public float Red { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"green")]
        public float Green { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"blue")]
        public float Blue { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"alpha")]
        public float Alpha { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Version : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"major_version")]
        public uint MajorVersion { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"minor_version")]
        public uint MinorVersion { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"patch_version")]
        public uint PatchVersion { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"build")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Build { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ApplicationInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Platform platform { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"platform_version")]
        public Version PlatformVersion { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Application application { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"application_version")]
        public Version ApplicationVersion { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Platform
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_UNDEFINED")]
            PlatformUndefined = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_MACOS")]
            PlatformMacos = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_WINDOWS")]
            PlatformWindows = 2,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum Application
        {
            [global::ProtoBuf.ProtoEnum(Name = @"APPLICATION_UNDEFINED")]
            ApplicationUndefined = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"APPLICATION_PROPRESENTER")]
            ApplicationPropresenter = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"APPLICATION_PVP")]
            ApplicationPvp = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"APPLICATION_PROVIDEOSERVER")]
            ApplicationProvideoserver = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"APPLICATION_SCOREBOARD")]
            ApplicationScoreboard = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CollectionElementType : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"parameter_uuid")]
        public Uuid ParameterUuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"parameter_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ParameterName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MusicKeyScale : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public MusicKey music_key { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public MusicScale music_scale { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum MusicKey
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_A_FLAT")]
            MusicKeyAFlat = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_A")]
            MusicKeyA = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_A_SHARP")]
            MusicKeyASharp = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_B_FLAT")]
            MusicKeyBFlat = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_B")]
            MusicKeyB = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_B_SHARP")]
            MusicKeyBSharp = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_C_FLAT")]
            MusicKeyCFlat = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_C")]
            MusicKeyC = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_C_SHARP")]
            MusicKeyCSharp = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_D_FLAT")]
            MusicKeyDFlat = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_D")]
            MusicKeyD = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_D_SHARP")]
            MusicKeyDSharp = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_E_FLAT")]
            MusicKeyEFlat = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_E")]
            MusicKeyE = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_E_SHARP")]
            MusicKeyESharp = 14,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_F_FLAT")]
            MusicKeyFFlat = 15,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_F")]
            MusicKeyF = 16,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_F_SHARP")]
            MusicKeyFSharp = 17,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_G_FLAT")]
            MusicKeyGFlat = 18,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_G")]
            MusicKeyG = 19,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_KEY_G_SHARP")]
            MusicKeyGSharp = 20,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum MusicScale
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_SCALE_MAJOR")]
            MusicScaleMajor = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MUSIC_SCALE_MINOR")]
            MusicScaleMinor = 1,
        }

    }

}


#endregion
