// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: calendar.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Calendar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"events")]
        public global::System.Collections.Generic.List<Event> Events { get; } = new global::System.Collections.Generic.List<Event>();

        [global::ProtoBuf.ProtoMember(2, Name = @"active")]
        public bool Active { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Event : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
            public Uuid Uuid { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"description")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Description { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4, Name = @"date")]
            public Timestamp Date { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"recurrence_days", IsPacked = true)]
            public global::System.Collections.Generic.List<DayOfWeek> RecurrenceDays { get; } = new global::System.Collections.Generic.List<DayOfWeek>();

            [global::ProtoBuf.ProtoMember(6, Name = @"recurrence_limit_date")]
            public Timestamp RecurrenceLimitDate { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"recurrence_excluded_dates")]
            public global::System.Collections.Generic.List<Timestamp> RecurrenceExcludedDates { get; } = new global::System.Collections.Generic.List<Timestamp>();

            [global::ProtoBuf.ProtoMember(8)]
            public Action action { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class Action : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"type")]
                public uint Type { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"uuid")]
                public Uuid Uuid { get; set; }

                [global::ProtoBuf.ProtoMember(3)]
                public Playlist playlist
                {
                    get => __pbn__ActionType.Is(3) ? ((Playlist)__pbn__ActionType.Object) : default;
                    set => __pbn__ActionType = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
                }
                public bool ShouldSerializeplaylist() => __pbn__ActionType.Is(3);
                public void Resetplaylist() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ActionType, 3);

                private global::ProtoBuf.DiscriminatedUnionObject __pbn__ActionType;

                [global::ProtoBuf.ProtoMember(4)]
                public Macro macro
                {
                    get => __pbn__ActionType.Is(4) ? ((Macro)__pbn__ActionType.Object) : default;
                    set => __pbn__ActionType = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
                }
                public bool ShouldSerializemacro() => __pbn__ActionType.Is(4);
                public void Resetmacro() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ActionType, 4);

                [global::ProtoBuf.ProtoContract()]
                public partial class Playlist : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"playlist_uuid")]
                    public Uuid PlaylistUuid { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"playlist_item_uuid")]
                    public Uuid PlaylistItemUuid { get; set; }

                }

                [global::ProtoBuf.ProtoContract()]
                public partial class Macro : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"identification")]
                    public CollectionElementType Identification { get; set; }

                }

            }

            [global::ProtoBuf.ProtoContract()]
            public enum DayOfWeek
            {
                [global::ProtoBuf.ProtoEnum(Name = @"DAY_OF_WEEK_UNKNOWN")]
                DayOfWeekUnknown = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"DAY_OF_WEEK_SUNDAY")]
                DayOfWeekSunday = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"DAY_OF_WEEK_MONDAY")]
                DayOfWeekMonday = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"DAY_OF_WEEK_TUESDAY")]
                DayOfWeekTuesday = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"DAY_OF_WEEK_WEDNESDAY")]
                DayOfWeekWednesday = 4,
                [global::ProtoBuf.ProtoEnum(Name = @"DAY_OF_WEEK_THURSDAY")]
                DayOfWeekThursday = 5,
                [global::ProtoBuf.ProtoEnum(Name = @"DAY_OF_WEEK_FRIDAY")]
                DayOfWeekFriday = 6,
                [global::ProtoBuf.ProtoEnum(Name = @"DAY_OF_WEEK_SATURDAY")]
                DayOfWeekSaturday = 7,
            }

        }

    }

}


#endregion
