// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: clearGroups.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ClearGroupsDocument : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"application_info")]
        public ApplicationInfo ApplicationInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"groups")]
        public global::System.Collections.Generic.List<ClearGroup> Groups { get; } = new global::System.Collections.Generic.List<ClearGroup>();

        [global::ProtoBuf.ProtoContract()]
        public partial class ClearGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
            public Uuid Uuid { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"layer_targets")]
            public global::System.Collections.Generic.List<Action.ClearType> LayerTargets { get; } = new global::System.Collections.Generic.List<Action.ClearType>();

            [global::ProtoBuf.ProtoMember(4, Name = @"is_hidden_in_preview")]
            public bool IsHiddenInPreview { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"image_data")]
            public byte[] ImageData { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            public ImageType image_type { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"is_icon_tinted")]
            public bool IsIconTinted { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"icon_tint_color")]
            public Color IconTintColor { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"timeline_targets", IsPacked = true)]
            public global::System.Collections.Generic.List<ContentDestination> TimelineTargets { get; } = new global::System.Collections.Generic.List<ContentDestination>();

            [global::ProtoBuf.ProtoMember(10, Name = @"clear_presentation_next_slide")]
            public bool ClearPresentationNextSlide { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum ImageType
            {
                ImageTypeCustom = 0,
                ImageTypeOne = 1,
                ImageTypeTwo = 2,
                ImageTypeThree = 3,
                ImageTypeFour = 4,
                ImageTypeFive = 5,
                ImageTypeSix = 6,
                ImageTypeSeven = 7,
                ImageTypeEight = 8,
                ImageTypeNine = 9,
                ImageTypeZero = 10,
                ImageTypeAll = 11,
                ImageTypeMegahorn = 12,
                ImageTypePlay = 13,
                ImageTypeBulb = 14,
                ImageTypeSunglasses = 15,
                ImageTypeArrow = 16,
                ImageTypeTarget = 17,
                ImageTypeStar = 18,
                ImageTypeSun = 19,
                ImageTypeBell = 20,
                ImageTypePaperclip = 21,
                ImageTypeFlask = 22,
                ImageTypeEyeglasses = 23,
                ImageTypeCupcake = 24,
                ImageTypeSlide = 25,
                ImageTypeHat = 26,
                ImageTypeFlower = 27,
                ImageTypeHeart = 28,
                ImageTypeMessage = 29,
                ImageTypeAudio = 30,
                ImageTypeCloud = 31,
                ImageTypeExclamation = 32,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum ContentDestination
            {
                [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_DESTINATION_GLOBAL")]
                ContentDestinationGlobal = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_DESTINATION_ANNOUNCEMENTS")]
                ContentDestinationAnnouncements = 1,
            }

        }

    }

}


#endregion
