// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cue.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Cue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public CompletionTargetType completion_target_type { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"completion_target_uuid")]
        public Uuid CompletionTargetUuid { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public CompletionActionType completion_action_type { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"completion_action_uuid")]
        public Uuid CompletionActionUuid { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"trigger_time")]
        public TimecodeTime TriggerTime { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"hot_key")]
        public HotKey HotKey { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"actions")]
        public global::System.Collections.Generic.List<Action> Actions { get; } = new global::System.Collections.Generic.List<Action>();

        [global::ProtoBuf.ProtoMember(11, Name = @"pending_imports")]
        public global::System.Collections.Generic.List<PendingImportsEntry> PendingImports { get; } = new global::System.Collections.Generic.List<PendingImportsEntry>();

        [global::ProtoBuf.ProtoMember(12)]
        public bool isEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"completion_time")]
        public double CompletionTime { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class TimecodeTime : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"time")]
            public double Time { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class PendingImportsEntry : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"key")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Key { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"value")]
            public URLs Value { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum CompletionTargetType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLETION_TARGET_TYPE_NONE")]
            CompletionTargetTypeNone = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLETION_TARGET_TYPE_NEXT")]
            CompletionTargetTypeNext = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLETION_TARGET_TYPE_RANDOM")]
            CompletionTargetTypeRandom = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLETION_TARGET_TYPE_CUE")]
            CompletionTargetTypeCue = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLETION_TARGET_TYPE_FIRST")]
            CompletionTargetTypeFirst = 4,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum CompletionActionType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLETION_ACTION_TYPE_FIRST")]
            CompletionActionTypeFirst = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLETION_ACTION_TYPE_LAST")]
            CompletionActionTypeLast = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLETION_ACTION_TYPE_AFTER_ACTION")]
            CompletionActionTypeAfterAction = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"COMPLETION_ACTION_TYPE_AFTER_TIME")]
            CompletionActionTypeAfterTime = 3,
        }

    }

}


#endregion
