// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: graphicsData.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Graphics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoContract()]
        public partial class Element : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
            public Uuid Uuid { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"bounds")]
            public Graphics.Rect Bounds { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"rotation")]
            public double Rotation { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"opacity")]
            public double Opacity { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"locked")]
            public bool Locked { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"aspect_ratio_locked")]
            public bool AspectRatioLocked { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"path")]
            public Graphics.Path Path { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"fill")]
            public Graphics.Fill Fill { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"stroke")]
            public Graphics.Stroke Stroke { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"shadow")]
            public Graphics.Shadow Shadow { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"feather")]
            public Graphics.Feather Feather { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"text")]
            public Graphics.Text Text { get; set; }

            [global::ProtoBuf.ProtoMember(15)]
            public FlipMode flipMode { get; set; }

            [global::ProtoBuf.ProtoMember(16, Name = @"hidden")]
            public bool Hidden { get; set; }

            [global::ProtoBuf.ProtoMember(14, Name = @"text_line_mask")]
            public Graphics.Text.LineFillMask TextLineMask { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum FlipMode
            {
                [global::ProtoBuf.ProtoEnum(Name = @"FLIP_MODE_NONE")]
                FlipModeNone = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"FLIP_MODE_VERTICAL")]
                FlipModeVertical = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"FLIP_MODE_HORIZONTAL")]
                FlipModeHorizontal = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"FLIP_MODE_BOTH")]
                FlipModeBoth = 3,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Rect : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"origin")]
            public Graphics.Point Origin { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"size")]
            public Graphics.Size Size { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Point : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"x")]
            public double X { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"y")]
            public double Y { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Size : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"width")]
            public double Width { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"height")]
            public double Height { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EdgeInsets : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"left")]
            public double Left { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"right")]
            public double Right { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"top")]
            public double Top { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"bottom")]
            public double Bottom { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Path : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"closed")]
            public bool Closed { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"points")]
            public global::System.Collections.Generic.List<BezierPoint> Points { get; } = new global::System.Collections.Generic.List<BezierPoint>();

            [global::ProtoBuf.ProtoMember(3)]
            public Shape shape { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class BezierPoint : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"point")]
                public Graphics.Point Point { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"q0")]
                public Graphics.Point Q0 { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"q1")]
                public Graphics.Point Q1 { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"curved")]
                public bool Curved { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Shape : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                public Type type { get; set; }

                [global::ProtoBuf.ProtoMember(2)]
                public RoundedRectangle rounded_rectangle
                {
                    get => __pbn__AdditionalData.Is(2) ? ((RoundedRectangle)__pbn__AdditionalData.Object) : default;
                    set => __pbn__AdditionalData = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
                }
                public bool ShouldSerializerounded_rectangle() => __pbn__AdditionalData.Is(2);
                public void Resetrounded_rectangle() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__AdditionalData, 2);

                private global::ProtoBuf.DiscriminatedUnionObject __pbn__AdditionalData;

                [global::ProtoBuf.ProtoMember(3)]
                public Polygon polygon
                {
                    get => __pbn__AdditionalData.Is(3) ? ((Polygon)__pbn__AdditionalData.Object) : default;
                    set => __pbn__AdditionalData = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
                }
                public bool ShouldSerializepolygon() => __pbn__AdditionalData.Is(3);
                public void Resetpolygon() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__AdditionalData, 3);

                [global::ProtoBuf.ProtoMember(4)]
                public Star star
                {
                    get => __pbn__AdditionalData.Is(4) ? ((Star)__pbn__AdditionalData.Object) : default;
                    set => __pbn__AdditionalData = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
                }
                public bool ShouldSerializestar() => __pbn__AdditionalData.Is(4);
                public void Resetstar() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__AdditionalData, 4);

                [global::ProtoBuf.ProtoMember(5)]
                public Arrow arrow
                {
                    get => __pbn__AdditionalData.Is(5) ? ((Arrow)__pbn__AdditionalData.Object) : default;
                    set => __pbn__AdditionalData = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
                }
                public bool ShouldSerializearrow() => __pbn__AdditionalData.Is(5);
                public void Resetarrow() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__AdditionalData, 5);

                [global::ProtoBuf.ProtoContract()]
                public partial class RoundedRectangle : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"roundness")]
                    public double Roundness { get; set; }

                }

                [global::ProtoBuf.ProtoContract()]
                public partial class Arrow : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"corner")]
                    public Graphics.Point Corner { get; set; }

                }

                [global::ProtoBuf.ProtoContract()]
                public partial class Polygon : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"number_sides")]
                    public uint NumberSides { get; set; }

                }

                [global::ProtoBuf.ProtoContract()]
                public partial class Star : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"inner_radius")]
                    public double InnerRadius { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"number_points")]
                    public uint NumberPoints { get; set; }

                }

                [global::ProtoBuf.ProtoContract()]
                public enum Type
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_UNKNOWN")]
                    TypeUnknown = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_RECTANGLE")]
                    TypeRectangle = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_ELLIPSE")]
                    TypeEllipse = 2,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_ISOSCELES_TRIANGLE")]
                    TypeIsoscelesTriangle = 3,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_RIGHT_TRIANGLE")]
                    TypeRightTriangle = 4,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_RHOMBUS")]
                    TypeRhombus = 5,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_STAR")]
                    TypeStar = 6,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_POLYGON")]
                    TypePolygon = 7,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_CUSTOM")]
                    TypeCustom = 8,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_RIGHT_ARROW")]
                    TypeRightArrow = 9,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_DOUBLE_ARROW")]
                    TypeDoubleArrow = 10,
                    [global::ProtoBuf.ProtoEnum(Name = @"TYPE_ROUNDED_RECTANGLE")]
                    TypeRoundedRectangle = 11,
                }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Fill : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(4, Name = @"enable")]
            public bool Enable { get; set; }

            [global::ProtoBuf.ProtoMember(1, Name = @"color")]
            public Color Color
            {
                get => __pbn__FillType.Is(1) ? ((Color)__pbn__FillType.Object) : default;
                set => __pbn__FillType = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
            }
            public bool ShouldSerializeColor() => __pbn__FillType.Is(1);
            public void ResetColor() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__FillType, 1);

            private global::ProtoBuf.DiscriminatedUnionObject __pbn__FillType;

            [global::ProtoBuf.ProtoMember(2, Name = @"gradient")]
            public Graphics.Gradient Gradient
            {
                get => __pbn__FillType.Is(2) ? ((Graphics.Gradient)__pbn__FillType.Object) : default;
                set => __pbn__FillType = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
            }
            public bool ShouldSerializeGradient() => __pbn__FillType.Is(2);
            public void ResetGradient() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__FillType, 2);

            [global::ProtoBuf.ProtoMember(3, Name = @"media")]
            public Media Media
            {
                get => __pbn__FillType.Is(3) ? ((Media)__pbn__FillType.Object) : default;
                set => __pbn__FillType = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
            }
            public bool ShouldSerializeMedia() => __pbn__FillType.Is(3);
            public void ResetMedia() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__FillType, 3);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Gradient : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public Type type { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"angle")]
            public double Angle { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"length")]
            public double Length { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"stops")]
            public global::System.Collections.Generic.List<ColorStop> Stops { get; } = new global::System.Collections.Generic.List<ColorStop>();

            [global::ProtoBuf.ProtoContract()]
            public partial class ColorStop : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"color")]
                public Color Color { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"position")]
                public double Position { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"blend_point")]
                public double BlendPoint { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public enum Type
            {
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_LINEAR")]
                TypeLinear = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_RADIAL")]
                TypeRadial = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_ANGLE")]
                TypeAngle = 2,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Shadow : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public Style style { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"angle")]
            public double Angle { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"offset")]
            public double Offset { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"radius")]
            public double Radius { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"color")]
            public Color Color { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"opacity")]
            public double Opacity { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"enable")]
            public bool Enable { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum Style
            {
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_DROP")]
                StyleDrop = 0,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Stroke : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public Style style { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"width")]
            public double Width { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"color")]
            public Color Color { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"pattern", IsPacked = true)]
            public double[] Patterns { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"enable")]
            public bool Enable { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum Style
            {
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_SOLID_LINE")]
                StyleSolidLine = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_SQUARE_DASH")]
                StyleSquareDash = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_SHORT_DASH")]
                StyleShortDash = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_LONG_DASH")]
                StyleLongDash = 3,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Feather : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public Style style { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"radius")]
            public double Radius { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"enable")]
            public bool Enable { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum Style
            {
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_INSIDE")]
                StyleInside = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_CENTER")]
                StyleCenter = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_OUTSIDE")]
                StyleOutside = 2,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Text : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(3)]
            public Attributes attributes { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"shadow")]
            public Graphics.Shadow Shadow { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"rtf_data")]
            public byte[] RtfData { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            public VerticalAlignment vertical_alignment { get; set; }

            [global::ProtoBuf.ProtoMember(7)]
            public ScaleBehavior scale_behavior { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"margins")]
            public Graphics.EdgeInsets Margins { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"is_superscript_standardized")]
            public bool IsSuperscriptStandardized { get; set; }

            [global::ProtoBuf.ProtoMember(10)]
            public Transform transform { get; set; }

            [global::ProtoBuf.ProtoMember(11)]
            [global::System.ComponentModel.DefaultValue("")]
            public string transformDelimiter { get; set; } = "";

            [global::ProtoBuf.ProtoMember(12)]
            public ChordPro chord_pro { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class LineFillMask : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"enabled")]
                public bool Enabled { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"height_offset")]
                public double HeightOffset { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"vertical_offset")]
                public double VerticalOffset { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"mask_style")]
                public LineMaskStyle MaskStyle { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"width_offset")]
                public double WidthOffset { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"horizontal_offset")]
                public double HorizontalOffset { get; set; }

                [global::ProtoBuf.ProtoContract()]
                public enum LineMaskStyle
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"LINE_MASK_STYLE_FULL_WIDTH")]
                    LineMaskStyleFullWidth = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"LINE_MASK_STYLE_LINE_WIDTH")]
                    LineMaskStyleLineWidth = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"LINE_MASK_STYLE_MAX_LINE_WIDTH")]
                    LineMaskStyleMaxLineWidth = 2,
                }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class GradientFill : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"gradient")]
                public Graphics.Gradient Gradient { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"stretch_to_document_bounds")]
                public bool StretchToDocumentBounds { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class ChordPro : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"enabled")]
                public bool Enabled { get; set; }

                [global::ProtoBuf.ProtoMember(2)]
                public Notation notation { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"color")]
                public Color Color { get; set; }

                [global::ProtoBuf.ProtoContract()]
                public enum Notation
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"NOTATION_CHORDS")]
                    NotationChords = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"NOTATION_NUMBERS")]
                    NotationNumbers = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"NOTATION_NUMERALS")]
                    NotationNumerals = 2,
                    [global::ProtoBuf.ProtoEnum(Name = @"NOTATION_DO_RE_MI")]
                    NotationDoReMi = 3,
                }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Attributes : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                public Font font { get; set; }

                [global::ProtoBuf.ProtoMember(2)]
                public Capitalization capitalization { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"underline_style")]
                public Underline UnderlineStyle { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"underline_color")]
                public Color UnderlineColor { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"paragraph_style")]
                public Paragraph ParagraphStyle { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"kerning")]
                public double Kerning { get; set; }

                [global::ProtoBuf.ProtoMember(8, Name = @"superscript")]
                public int Superscript { get; set; }

                [global::ProtoBuf.ProtoMember(9, Name = @"strikethrough_style")]
                public Underline StrikethroughStyle { get; set; }

                [global::ProtoBuf.ProtoMember(10, Name = @"strikethrough_color")]
                public Color StrikethroughColor { get; set; }

                [global::ProtoBuf.ProtoMember(11, Name = @"stroke_width")]
                public double StrokeWidth { get; set; }

                [global::ProtoBuf.ProtoMember(12, Name = @"stroke_color")]
                public Color StrokeColor { get; set; }

                [global::ProtoBuf.ProtoMember(13, Name = @"custom_attributes")]
                public global::System.Collections.Generic.List<CustomAttribute> CustomAttributes { get; } = new global::System.Collections.Generic.List<CustomAttribute>();

                [global::ProtoBuf.ProtoMember(15, Name = @"background_color")]
                public Color BackgroundColor { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"text_solid_fill")]
                public Color TextSolidFill
                {
                    get => __pbn__fill.Is(3) ? ((Color)__pbn__fill.Object) : default;
                    set => __pbn__fill = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
                }
                public bool ShouldSerializeTextSolidFill() => __pbn__fill.Is(3);
                public void ResetTextSolidFill() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__fill, 3);

                private global::ProtoBuf.DiscriminatedUnionObject __pbn__fill;

                [global::ProtoBuf.ProtoMember(14, Name = @"text_gradient_fill")]
                public Graphics.Text.GradientFill TextGradientFill
                {
                    get => __pbn__fill.Is(14) ? ((Graphics.Text.GradientFill)__pbn__fill.Object) : default;
                    set => __pbn__fill = new global::ProtoBuf.DiscriminatedUnionObject(14, value);
                }
                public bool ShouldSerializeTextGradientFill() => __pbn__fill.Is(14);
                public void ResetTextGradientFill() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__fill, 14);

                [global::ProtoBuf.ProtoContract()]
                public partial class Font : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"name")]
                    [global::System.ComponentModel.DefaultValue("")]
                    public string Name { get; set; } = "";

                    [global::ProtoBuf.ProtoMember(2, Name = @"size")]
                    public double Size { get; set; }

                    [global::ProtoBuf.ProtoMember(4, Name = @"italic")]
                    public bool Italic { get; set; }

                    [global::ProtoBuf.ProtoMember(8, Name = @"bold")]
                    public bool Bold { get; set; }

                    [global::ProtoBuf.ProtoMember(9, Name = @"family")]
                    [global::System.ComponentModel.DefaultValue("")]
                    public string Family { get; set; } = "";

                    [global::ProtoBuf.ProtoMember(10, Name = @"face")]
                    [global::System.ComponentModel.DefaultValue("")]
                    public string Face { get; set; } = "";

                }

                [global::ProtoBuf.ProtoContract()]
                public partial class Underline : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1)]
                    public Style style { get; set; }

                    [global::ProtoBuf.ProtoMember(2)]
                    public Pattern pattern { get; set; }

                    [global::ProtoBuf.ProtoMember(3, Name = @"by_word")]
                    public bool ByWord { get; set; }

                    [global::ProtoBuf.ProtoContract()]
                    public enum Style
                    {
                        [global::ProtoBuf.ProtoEnum(Name = @"STYLE_NONE")]
                        StyleNone = 0,
                        [global::ProtoBuf.ProtoEnum(Name = @"STYLE_SINGLE")]
                        StyleSingle = 1,
                        [global::ProtoBuf.ProtoEnum(Name = @"STYLE_THICK")]
                        StyleThick = 2,
                        [global::ProtoBuf.ProtoEnum(Name = @"STYLE_DOUBLE")]
                        StyleDouble = 3,
                    }

                    [global::ProtoBuf.ProtoContract()]
                    public enum Pattern
                    {
                        [global::ProtoBuf.ProtoEnum(Name = @"PATTERN_SOLID")]
                        PatternSolid = 0,
                        [global::ProtoBuf.ProtoEnum(Name = @"PATTERN_DOT")]
                        PatternDot = 1,
                        [global::ProtoBuf.ProtoEnum(Name = @"PATTERN_DASH")]
                        PatternDash = 2,
                        [global::ProtoBuf.ProtoEnum(Name = @"PATTERN_DASH_DOT")]
                        PatternDashDot = 3,
                        [global::ProtoBuf.ProtoEnum(Name = @"PATTERN_DASH_DOT_DOT")]
                        PatternDashDotDot = 4,
                    }

                }

                [global::ProtoBuf.ProtoContract()]
                public partial class Paragraph : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1)]
                    public Alignment alignment { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"first_line_head_indent")]
                    public double FirstLineHeadIndent { get; set; }

                    [global::ProtoBuf.ProtoMember(3, Name = @"head_indent")]
                    public double HeadIndent { get; set; }

                    [global::ProtoBuf.ProtoMember(4, Name = @"tail_indent")]
                    public double TailIndent { get; set; }

                    [global::ProtoBuf.ProtoMember(5, Name = @"line_height_multiple")]
                    public double LineHeightMultiple { get; set; }

                    [global::ProtoBuf.ProtoMember(6, Name = @"maximum_line_height")]
                    public double MaximumLineHeight { get; set; }

                    [global::ProtoBuf.ProtoMember(7, Name = @"minimum_line_height")]
                    public double MinimumLineHeight { get; set; }

                    [global::ProtoBuf.ProtoMember(8, Name = @"line_spacing")]
                    public double LineSpacing { get; set; }

                    [global::ProtoBuf.ProtoMember(9, Name = @"paragraph_spacing")]
                    public double ParagraphSpacing { get; set; }

                    [global::ProtoBuf.ProtoMember(10, Name = @"paragraph_spacing_before")]
                    public double ParagraphSpacingBefore { get; set; }

                    [global::ProtoBuf.ProtoMember(11, Name = @"tab_stops")]
                    public global::System.Collections.Generic.List<TabStop> TabStops { get; } = new global::System.Collections.Generic.List<TabStop>();

                    [global::ProtoBuf.ProtoMember(12, Name = @"default_tab_interval")]
                    public double DefaultTabInterval { get; set; }

                    [global::ProtoBuf.ProtoMember(13)]
                    public TextList text_list { get; set; }

                    [global::ProtoBuf.ProtoMember(14, Name = @"text_lists")]
                    public global::System.Collections.Generic.List<TextList> TextLists { get; } = new global::System.Collections.Generic.List<TextList>();

                    [global::ProtoBuf.ProtoContract()]
                    public partial class TabStop : global::ProtoBuf.IExtensible
                    {
                        private global::ProtoBuf.IExtension __pbn__extensionData;
                        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                        [global::ProtoBuf.ProtoMember(1, Name = @"location")]
                        public double Location { get; set; }

                        [global::ProtoBuf.ProtoMember(2)]
                        public Alignment alignment { get; set; }

                        [global::ProtoBuf.ProtoContract()]
                        public enum Alignment
                        {
                            [global::ProtoBuf.ProtoEnum(Name = @"ALIGNMENT_LEFT")]
                            AlignmentLeft = 0,
                            [global::ProtoBuf.ProtoEnum(Name = @"ALIGNMENT_RIGHT")]
                            AlignmentRight = 1,
                            [global::ProtoBuf.ProtoEnum(Name = @"ALIGNMENT_CENTER")]
                            AlignmentCenter = 2,
                            [global::ProtoBuf.ProtoEnum(Name = @"ALIGNMENT_JUSTIFIED")]
                            AlignmentJustified = 3,
                            [global::ProtoBuf.ProtoEnum(Name = @"ALIGNMENT_NATURAL")]
                            AlignmentNatural = 4,
                        }

                    }

                    [global::ProtoBuf.ProtoContract()]
                    public partial class TextList : global::ProtoBuf.IExtensible
                    {
                        private global::ProtoBuf.IExtension __pbn__extensionData;
                        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                        [global::ProtoBuf.ProtoMember(1, Name = @"is_enabled")]
                        public bool IsEnabled { get; set; }

                        [global::ProtoBuf.ProtoMember(2)]
                        public NumberType number_type { get; set; }

                        [global::ProtoBuf.ProtoMember(3, Name = @"prefix")]
                        [global::System.ComponentModel.DefaultValue("")]
                        public string Prefix { get; set; } = "";

                        [global::ProtoBuf.ProtoMember(4, Name = @"postfix")]
                        [global::System.ComponentModel.DefaultValue("")]
                        public string Postfix { get; set; } = "";

                        [global::ProtoBuf.ProtoMember(5, Name = @"starting_number")]
                        public int StartingNumber { get; set; }

                        [global::ProtoBuf.ProtoContract()]
                        public enum NumberType
                        {
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_BOX")]
                            NumberTypeBox = 0,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_CHECK")]
                            NumberTypeCheck = 1,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_CIRCLE")]
                            NumberTypeCircle = 2,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_DIAMOND")]
                            NumberTypeDiamond = 3,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_DISC")]
                            NumberTypeDisc = 4,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_HYPHEN")]
                            NumberTypeHyphen = 5,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_SQUARE")]
                            NumberTypeSquare = 6,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_DECIMAL")]
                            NumberTypeDecimal = 7,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_LOWERCASE_ALPHA")]
                            NumberTypeLowercaseAlpha = 8,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_UPPERCASE_ALPHA")]
                            NumberTypeUppercaseAlpha = 9,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_LOWERCASE_ROMAN")]
                            NumberTypeLowercaseRoman = 10,
                            [global::ProtoBuf.ProtoEnum(Name = @"NUMBER_TYPE_UPPERCASE_ROMAN")]
                            NumberTypeUppercaseRoman = 11,
                        }

                    }

                    [global::ProtoBuf.ProtoContract()]
                    public enum Alignment
                    {
                        [global::ProtoBuf.ProtoEnum(Name = @"ALIGNMENT_LEFT")]
                        AlignmentLeft = 0,
                        [global::ProtoBuf.ProtoEnum(Name = @"ALIGNMENT_RIGHT")]
                        AlignmentRight = 1,
                        [global::ProtoBuf.ProtoEnum(Name = @"ALIGNMENT_CENTER")]
                        AlignmentCenter = 2,
                        [global::ProtoBuf.ProtoEnum(Name = @"ALIGNMENT_JUSTIFIED")]
                        AlignmentJustified = 3,
                        [global::ProtoBuf.ProtoEnum(Name = @"ALIGNMENT_NATURAL")]
                        AlignmentNatural = 4,
                    }

                }

                [global::ProtoBuf.ProtoContract()]
                public partial class CustomAttribute : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"range")]
                    public IntRange Range { get; set; }

                    [global::ProtoBuf.ProtoMember(2)]
                    public Capitalization capitalization
                    {
                        get => __pbn__Attribute.Is(2) ? ((Capitalization)__pbn__Attribute.Int32) : default;
                        set => __pbn__Attribute = new global::ProtoBuf.DiscriminatedUnion64Object(2, (int)value);
                    }
                    public bool ShouldSerializecapitalization() => __pbn__Attribute.Is(2);
                    public void Resetcapitalization() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__Attribute, 2);

                    private global::ProtoBuf.DiscriminatedUnion64Object __pbn__Attribute;

                    [global::ProtoBuf.ProtoMember(3, Name = @"original_font_size")]
                    public double OriginalFontSize
                    {
                        get => __pbn__Attribute.Is(3) ? __pbn__Attribute.Double : default;
                        set => __pbn__Attribute = new global::ProtoBuf.DiscriminatedUnion64Object(3, value);
                    }
                    public bool ShouldSerializeOriginalFontSize() => __pbn__Attribute.Is(3);
                    public void ResetOriginalFontSize() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__Attribute, 3);

                    [global::ProtoBuf.ProtoMember(4, Name = @"font_scale_factor")]
                    public double FontScaleFactor
                    {
                        get => __pbn__Attribute.Is(4) ? __pbn__Attribute.Double : default;
                        set => __pbn__Attribute = new global::ProtoBuf.DiscriminatedUnion64Object(4, value);
                    }
                    public bool ShouldSerializeFontScaleFactor() => __pbn__Attribute.Is(4);
                    public void ResetFontScaleFactor() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__Attribute, 4);

                    [global::ProtoBuf.ProtoMember(5, Name = @"text_gradient_fill")]
                    public Graphics.Text.GradientFill TextGradientFill
                    {
                        get => __pbn__Attribute.Is(5) ? ((Graphics.Text.GradientFill)__pbn__Attribute.Object) : default;
                        set => __pbn__Attribute = new global::ProtoBuf.DiscriminatedUnion64Object(5, value);
                    }
                    public bool ShouldSerializeTextGradientFill() => __pbn__Attribute.Is(5);
                    public void ResetTextGradientFill() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__Attribute, 5);

                    [global::ProtoBuf.ProtoMember(6, Name = @"should_preserve_foreground_color")]
                    public bool ShouldPreserveForegroundColor
                    {
                        get => __pbn__Attribute.Is(6) ? __pbn__Attribute.Boolean : default;
                        set => __pbn__Attribute = new global::ProtoBuf.DiscriminatedUnion64Object(6, value);
                    }
                    public bool ShouldSerializeShouldPreserveForegroundColor() => __pbn__Attribute.Is(6);
                    public void ResetShouldPreserveForegroundColor() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__Attribute, 6);

                    [global::ProtoBuf.ProtoMember(7, Name = @"chord")]
                    [global::System.ComponentModel.DefaultValue("")]
                    public string Chord
                    {
                        get => __pbn__Attribute.Is(7) ? ((string)__pbn__Attribute.Object) : "";
                        set => __pbn__Attribute = new global::ProtoBuf.DiscriminatedUnion64Object(7, value);
                    }
                    public bool ShouldSerializeChord() => __pbn__Attribute.Is(7);
                    public void ResetChord() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__Attribute, 7);

                    [global::ProtoBuf.ProtoContract()]
                    public enum Capitalization
                    {
                        [global::ProtoBuf.ProtoEnum(Name = @"CAPITALIZATION_NONE")]
                        CapitalizationNone = 0,
                        [global::ProtoBuf.ProtoEnum(Name = @"CAPITALIZATION_ALL_CAPS")]
                        CapitalizationAllCaps = 1,
                        [global::ProtoBuf.ProtoEnum(Name = @"CAPITALIZATION_SMALL_CAPS")]
                        CapitalizationSmallCaps = 2,
                        [global::ProtoBuf.ProtoEnum(Name = @"CAPITALIZATION_TITLE_CASE")]
                        CapitalizationTitleCase = 3,
                        [global::ProtoBuf.ProtoEnum(Name = @"CAPITALIZATION_START_CASE")]
                        CapitalizationStartCase = 4,
                    }

                }

                [global::ProtoBuf.ProtoContract()]
                public enum Capitalization
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"CAPITALIZATION_NONE")]
                    CapitalizationNone = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"CAPITALIZATION_ALL_CAPS")]
                    CapitalizationAllCaps = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"CAPITALIZATION_SMALL_CAPS")]
                    CapitalizationSmallCaps = 2,
                    [global::ProtoBuf.ProtoEnum(Name = @"CAPITALIZATION_TITLE_CASE")]
                    CapitalizationTitleCase = 3,
                    [global::ProtoBuf.ProtoEnum(Name = @"CAPITALIZATION_START_CASE")]
                    CapitalizationStartCase = 4,
                }

            }

            [global::ProtoBuf.ProtoContract()]
            public enum VerticalAlignment
            {
                [global::ProtoBuf.ProtoEnum(Name = @"VERTICAL_ALIGNMENT_TOP")]
                VerticalAlignmentTop = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"VERTICAL_ALIGNMENT_MIDDLE")]
                VerticalAlignmentMiddle = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"VERTICAL_ALIGNMENT_BOTTOM")]
                VerticalAlignmentBottom = 2,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum ScaleBehavior
            {
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_NONE")]
                ScaleBehaviorNone = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_ADJUST_CONTAINER_HEIGHT")]
                ScaleBehaviorAdjustContainerHeight = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_SCALE_FONT_DOWN")]
                ScaleBehaviorScaleFontDown = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_SCALE_FONT_UP")]
                ScaleBehaviorScaleFontUp = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_SCALE_FONT_UP_DOWN")]
                ScaleBehaviorScaleFontUpDown = 4,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum Transform
            {
                [global::ProtoBuf.ProtoEnum(Name = @"TRANSFORM_NONE")]
                TransformNone = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"TRANSFORM_SINGLE_LINE")]
                TransformSingleLine = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"TRANSFORM_ONE_WORD_PER_LINE")]
                TransformOneWordPerLine = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"TRANSFORM_ONE_CHARACTER_PER_LINE")]
                TransformOneCharacterPerLine = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"TRANSFORM_REPLACE_LINE_RETURNS")]
                TransformReplaceLineReturns = 4,
            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Media : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"url")]
        public Url Url { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Metadata metadata { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public AudioTypeProperties audio
        {
            get => __pbn__TypeProperties.Is(4) ? ((AudioTypeProperties)__pbn__TypeProperties.Object) : default;
            set => __pbn__TypeProperties = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeaudio() => __pbn__TypeProperties.Is(4);
        public void Resetaudio() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TypeProperties, 4);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__TypeProperties;

        [global::ProtoBuf.ProtoMember(5, Name = @"image")]
        public ImageTypeProperties Image
        {
            get => __pbn__TypeProperties.Is(5) ? ((ImageTypeProperties)__pbn__TypeProperties.Object) : default;
            set => __pbn__TypeProperties = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeImage() => __pbn__TypeProperties.Is(5);
        public void ResetImage() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TypeProperties, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"video")]
        public VideoTypeProperties Video
        {
            get => __pbn__TypeProperties.Is(6) ? ((VideoTypeProperties)__pbn__TypeProperties.Object) : default;
            set => __pbn__TypeProperties = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializeVideo() => __pbn__TypeProperties.Is(6);
        public void ResetVideo() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TypeProperties, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"live_video")]
        public LiveVideoTypeProperties LiveVideo
        {
            get => __pbn__TypeProperties.Is(7) ? ((LiveVideoTypeProperties)__pbn__TypeProperties.Object) : default;
            set => __pbn__TypeProperties = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
        }
        public bool ShouldSerializeLiveVideo() => __pbn__TypeProperties.Is(7);
        public void ResetLiveVideo() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TypeProperties, 7);

        [global::ProtoBuf.ProtoMember(8, Name = @"web_content")]
        public WebContentTypeProperties WebContent
        {
            get => __pbn__TypeProperties.Is(8) ? ((WebContentTypeProperties)__pbn__TypeProperties.Object) : default;
            set => __pbn__TypeProperties = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
        }
        public bool ShouldSerializeWebContent() => __pbn__TypeProperties.Is(8);
        public void ResetWebContent() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TypeProperties, 8);

        [global::ProtoBuf.ProtoContract()]
        public partial class Metadata : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"manufacture_name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ManufactureName { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"manufacture_url")]
            public Url ManufactureUrl { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"information")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Information { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4, Name = @"artist")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Artist { get; set; } = "";

            [global::ProtoBuf.ProtoMember(5, Name = @"format")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Format { get; set; } = "";

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class VideoDevice : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public Type type { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"unique_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string UniqueId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4, Name = @"model_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ModelId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(5, Name = @"format_index")]
            public uint FormatIndex { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"audio_routing")]
            public DigitalAudio.Device.Routing AudioRouting { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum Type
            {
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_GENERIC")]
                TypeGeneric = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_DIRECTSHOW")]
                TypeDirectshow = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_BLACKMAGIC")]
                TypeBlackmagic = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_AJA")]
                TypeAja = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_AV")]
                TypeAv = 4,
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_SYPHON")]
                TypeSyphon = 5,
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_NDI")]
                TypeNdi = 6,
                [global::ProtoBuf.ProtoEnum(Name = @"TYPE_BLUEFISH")]
                TypeBluefish = 7,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class AudioDevice : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"unique_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string UniqueId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"model_id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ModelId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4, Name = @"channel_count")]
            public uint ChannelCount { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Audio : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoContract()]
            public partial class Channel : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"index")]
                public uint Index { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"muted")]
                public bool Muted { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"volume")]
                public double Volume { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"compress_limit")]
                public bool CompressLimit { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"outputs")]
                public global::System.Collections.Generic.List<Output> Outputs { get; } = new global::System.Collections.Generic.List<Output>();

                [global::ProtoBuf.ProtoContract()]
                public partial class Output : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(2, Name = @"channel_index")]
                    public int ChannelIndex { get; set; }

                }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class AudioProperties : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"volume")]
            public double Volume { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"audio_channels")]
            public global::System.Collections.Generic.List<Media.Audio.Channel> AudioChannels { get; } = new global::System.Collections.Generic.List<Media.Audio.Channel>();

            [global::ProtoBuf.ProtoMember(3, Name = @"is_custom_mapping")]
            public bool IsCustomMapping { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class TransportProperties : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"play_rate")]
            public double PlayRate { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"in_point")]
            public double InPoint { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"out_point")]
            public double OutPoint { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"fade_in_duration")]
            public double FadeInDuration { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"fade_out_duration")]
            public double FadeOutDuration { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"should_fade_in")]
            public bool ShouldFadeIn { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"should_fade_out")]
            public bool ShouldFadeOut { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"end_point")]
            public double EndPoint { get; set; }

            [global::ProtoBuf.ProtoMember(12)]
            public PlaybackBehavior playback_behavior { get; set; }

            [global::ProtoBuf.ProtoMember(13, Name = @"loop_time")]
            public double LoopTime { get; set; }

            [global::ProtoBuf.ProtoMember(14, Name = @"times_to_loop")]
            public uint TimesToLoop { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum PlaybackBehavior
            {
                [global::ProtoBuf.ProtoEnum(Name = @"PLAYBACK_BEHAVIOR_STOP")]
                PlaybackBehaviorStop = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"PLAYBACK_BEHAVIOR_LOOP")]
                PlaybackBehaviorLoop = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"PLAYBACK_BEHAVIOR_LOOP_FOR_COUNT")]
                PlaybackBehaviorLoopForCount = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"PLAYBACK_BEHAVIOR_LOOP_FOR_TIME")]
                PlaybackBehaviorLoopForTime = 3,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class DrawingProperties : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public ScaleBehavior scale_behavior { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public ScaleAlignment scale_alignment { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"flipped_horizontally")]
            public bool FlippedHorizontally { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"flipped_vertically")]
            public bool FlippedVertically { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"natural_size")]
            public Graphics.Size NaturalSize { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"custom_image_rotation")]
            public double CustomImageRotation { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"custom_image_bounds")]
            public Graphics.Rect CustomImageBounds { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"custom_image_aspect_locked")]
            public bool CustomImageAspectLocked { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"alpha_inverted")]
            public bool AlphaInverted { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"native_rotation")]
            public NativeRotationType NativeRotation { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"selected_effect_preset_uuid")]
            public Uuid SelectedEffectPresetUuid { get; set; }

            [global::ProtoBuf.ProtoMember(12, Name = @"effects")]
            public global::System.Collections.Generic.List<Effect> Effects { get; } = new global::System.Collections.Generic.List<Effect>();

            [global::ProtoBuf.ProtoMember(13, Name = @"crop_enable")]
            public bool CropEnable { get; set; }

            [global::ProtoBuf.ProtoMember(14, Name = @"crop_insets")]
            public Graphics.EdgeInsets CropInsets { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum ScaleBehavior
            {
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_FIT")]
                ScaleBehaviorFit = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_FILL")]
                ScaleBehaviorFill = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_STRETCH")]
                ScaleBehaviorStretch = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_CUSTOM")]
                ScaleBehaviorCustom = 3,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum ScaleAlignment
            {
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_MIDDLE_CENTER")]
                ScaleAlignmentMiddleCenter = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_TOP_LEFT")]
                ScaleAlignmentTopLeft = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_TOP_CENTER")]
                ScaleAlignmentTopCenter = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_TOP_RIGHT")]
                ScaleAlignmentTopRight = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_MIDDLE_RIGHT")]
                ScaleAlignmentMiddleRight = 4,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_BOTTOM_RIGHT")]
                ScaleAlignmentBottomRight = 5,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_BOTTOM_CENTER")]
                ScaleAlignmentBottomCenter = 6,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_BOTTOM_LEFT")]
                ScaleAlignmentBottomLeft = 7,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_MIDDLE_LEFT")]
                ScaleAlignmentMiddleLeft = 8,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum NativeRotationType
            {
                [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_STANDARD")]
                NativeRotationTypeRotateStandard = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_90")]
                NativeRotationTypeRotate90 = 90,
                [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_180")]
                NativeRotationTypeRotate180 = 180,
                [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_270")]
                NativeRotationTypeRotate270 = 270,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class VideoProperties : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"frame_rate")]
            public double FrameRate { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public FieldType field_type { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"thumbnail_position")]
            public double ThumbnailPosition { get; set; }

            [global::ProtoBuf.ProtoMember(4)]
            public EndBehavior end_behavior { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"soft_loop")]
            public bool SoftLoop { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"soft_loop_duration")]
            public double SoftLoopDuration { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum FieldType
            {
                [global::ProtoBuf.ProtoEnum(Name = @"FIELD_TYPE_UNKNOWN")]
                FieldTypeUnknown = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"FIELD_TYPE_PROGRESSIVE")]
                FieldTypeProgressive = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"FIELD_TYPE_INTERLACED_UPPER_FIRST")]
                FieldTypeInterlacedUpperFirst = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"FIELD_TYPE_INTERLACED_LOWER_FIRST")]
                FieldTypeInterlacedLowerFirst = 3,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum EndBehavior
            {
                [global::ProtoBuf.ProtoEnum(Name = @"END_BEHAVIOR_STOP")]
                EndBehaviorStop = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"END_BEHAVIOR_STOP_ON_BLACK")]
                EndBehaviorStopOnBlack = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"END_BEHAVIOR_STOP_ON_CLEAR")]
                EndBehaviorStopOnClear = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"END_BEHAVIOR_FADE_TO_BLACK")]
                EndBehaviorFadeToBlack = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"END_BEHAVIOR_FADE_TO_CLEAR")]
                EndBehaviorFadeToClear = 4,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class LiveVideoProperties : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"video_device")]
            public Media.VideoDevice VideoDevice { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"audio_device")]
            public Media.AudioDevice AudioDevice { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"live_video_index")]
            public int LiveVideoIndex { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class AudioTypeProperties : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"audio")]
            public Media.AudioProperties Audio { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"transport")]
            public Media.TransportProperties Transport { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ImageTypeProperties : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"drawing")]
            public Media.DrawingProperties Drawing { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class VideoTypeProperties : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"drawing")]
            public Media.DrawingProperties Drawing { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"audio")]
            public Media.AudioProperties Audio { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"transport")]
            public Media.TransportProperties Transport { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"video")]
            public Media.VideoProperties Video { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class LiveVideoTypeProperties : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"drawing")]
            public Media.DrawingProperties Drawing { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"audio")]
            public Media.AudioProperties Audio { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"live_video")]
            public Media.LiveVideoProperties LiveVideo { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class WebContentTypeProperties : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"drawing")]
            public Media.DrawingProperties Drawing { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"url")]
            public Url Url { get; set; }

        }

    }

}


#endregion
