// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: groups.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Group : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"color")]
        public Color Color { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public HotKey hotKey { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"application_group_identifier")]
        public Uuid ApplicationGroupIdentifier { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"application_group_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ApplicationGroupName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProGroupsDocument : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"groups")]
        public global::System.Collections.Generic.List<Group> Groups { get; } = new global::System.Collections.Generic.List<Group>();

    }

}


#endregion
