// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: input.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class VideoInput : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user_description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserDescription { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"video_input_device")]
        public Media.VideoDevice VideoInputDevice { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"display_color")]
        public Color DisplayColor { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"thumbnail_path")]
        public Url ThumbnailPath { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"audio_type")]
        public AudioDeviceType AudioType { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"audio_device")]
        public DigitalAudio.Device AudioDevice
        {
            get => __pbn__AltAudioSource.Is(6) ? ((DigitalAudio.Device)__pbn__AltAudioSource.Object) : default;
            set => __pbn__AltAudioSource = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializeAudioDevice() => __pbn__AltAudioSource.Is(6);
        public void ResetAudioDevice() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__AltAudioSource, 6);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__AltAudioSource;

        [global::ProtoBuf.ProtoMember(7, Name = @"video_device")]
        public Media.VideoDevice VideoDevice
        {
            get => __pbn__AltAudioSource.Is(7) ? ((Media.VideoDevice)__pbn__AltAudioSource.Object) : default;
            set => __pbn__AltAudioSource = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
        }
        public bool ShouldSerializeVideoDevice() => __pbn__AltAudioSource.Is(7);
        public void ResetVideoDevice() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__AltAudioSource, 7);

        [global::ProtoBuf.ProtoContract()]
        public partial class SettingsDocument : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"inputs")]
            public global::System.Collections.Generic.List<VideoInput> Inputs { get; } = new global::System.Collections.Generic.List<VideoInput>();

        }

        [global::ProtoBuf.ProtoContract()]
        public enum AudioDeviceType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_DEVICE_TYPE_DEFAULT")]
            AudioDeviceTypeDefault = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_DEVICE_TYPE_NONE")]
            AudioDeviceTypeNone = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"AUDIO_DEVICE_TYPE_ALTERNATE")]
            AudioDeviceTypeAlternate = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AudioInput : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"user_description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserDescription { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public BehaviorMode behavior_mode { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"audio_device")]
        public DigitalAudio.Device AudioDevice
        {
            get => __pbn__Source.Is(3) ? ((DigitalAudio.Device)__pbn__Source.Object) : default;
            set => __pbn__Source = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeAudioDevice() => __pbn__Source.Is(3);
        public void ResetAudioDevice() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Source, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__Source;

        [global::ProtoBuf.ProtoMember(4, Name = @"video_device")]
        public Media.VideoDevice VideoDevice
        {
            get => __pbn__Source.Is(4) ? ((Media.VideoDevice)__pbn__Source.Object) : default;
            set => __pbn__Source = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeVideoDevice() => __pbn__Source.Is(4);
        public void ResetVideoDevice() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Source, 4);

        [global::ProtoBuf.ProtoContract()]
        public partial class BehaviorMode : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public On on
            {
                get => __pbn__Mode.Is(1) ? ((On)__pbn__Mode.Object) : default;
                set => __pbn__Mode = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
            }
            public bool ShouldSerializeon() => __pbn__Mode.Is(1);
            public void Reseton() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Mode, 1);

            private global::ProtoBuf.DiscriminatedUnionObject __pbn__Mode;

            [global::ProtoBuf.ProtoMember(2)]
            public Off off
            {
                get => __pbn__Mode.Is(2) ? ((Off)__pbn__Mode.Object) : default;
                set => __pbn__Mode = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
            }
            public bool ShouldSerializeoff() => __pbn__Mode.Is(2);
            public void Resetoff() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Mode, 2);

            [global::ProtoBuf.ProtoMember(3)]
            public AutoOn auto_on
            {
                get => __pbn__Mode.Is(3) ? ((AutoOn)__pbn__Mode.Object) : default;
                set => __pbn__Mode = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
            }
            public bool ShouldSerializeauto_on() => __pbn__Mode.Is(3);
            public void Resetauto_on() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Mode, 3);

            [global::ProtoBuf.ProtoMember(4)]
            public AutoOff auto_off
            {
                get => __pbn__Mode.Is(4) ? ((AutoOff)__pbn__Mode.Object) : default;
                set => __pbn__Mode = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
            }
            public bool ShouldSerializeauto_off() => __pbn__Mode.Is(4);
            public void Resetauto_off() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Mode, 4);

            [global::ProtoBuf.ProtoContract()]
            public partial class On : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Off : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class AutoOff : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class AutoOn : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"linked_video_inputs", IsPacked = true)]
                public uint[] LinkedVideoInputs { get; set; }

            }

        }

    }

}


#endregion
