// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: keymapping.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class KeyMapping : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"keyboard")]
        public ComputerKeyboard Keyboard { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"midi")]
        public MIDIKeyboard Midi { get; set; }

        [global::ProtoBuf.ProtoMember(100, Name = @"menu_item")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MenuItem
        {
            get => __pbn__TargetIdentifier.Is(100) ? ((string)__pbn__TargetIdentifier.Object) : "";
            set => __pbn__TargetIdentifier = new global::ProtoBuf.DiscriminatedUnionObject(100, value);
        }
        public bool ShouldSerializeMenuItem() => __pbn__TargetIdentifier.Is(100);
        public void ResetMenuItem() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TargetIdentifier, 100);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__TargetIdentifier;

        [global::ProtoBuf.ProtoMember(101, Name = @"clear_group_identifier")]
        public CollectionElementType ClearGroupIdentifier
        {
            get => __pbn__TargetIdentifier.Is(101) ? ((CollectionElementType)__pbn__TargetIdentifier.Object) : default;
            set => __pbn__TargetIdentifier = new global::ProtoBuf.DiscriminatedUnionObject(101, value);
        }
        public bool ShouldSerializeClearGroupIdentifier() => __pbn__TargetIdentifier.Is(101);
        public void ResetClearGroupIdentifier() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TargetIdentifier, 101);

        [global::ProtoBuf.ProtoMember(102, Name = @"cue_identifier")]
        public CollectionElementType CueIdentifier
        {
            get => __pbn__TargetIdentifier.Is(102) ? ((CollectionElementType)__pbn__TargetIdentifier.Object) : default;
            set => __pbn__TargetIdentifier = new global::ProtoBuf.DiscriminatedUnionObject(102, value);
        }
        public bool ShouldSerializeCueIdentifier() => __pbn__TargetIdentifier.Is(102);
        public void ResetCueIdentifier() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TargetIdentifier, 102);

        [global::ProtoBuf.ProtoMember(103, Name = @"group_identifier")]
        public CollectionElementType GroupIdentifier
        {
            get => __pbn__TargetIdentifier.Is(103) ? ((CollectionElementType)__pbn__TargetIdentifier.Object) : default;
            set => __pbn__TargetIdentifier = new global::ProtoBuf.DiscriminatedUnionObject(103, value);
        }
        public bool ShouldSerializeGroupIdentifier() => __pbn__TargetIdentifier.Is(103);
        public void ResetGroupIdentifier() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TargetIdentifier, 103);

        [global::ProtoBuf.ProtoMember(104, Name = @"macro_identifier")]
        public CollectionElementType MacroIdentifier
        {
            get => __pbn__TargetIdentifier.Is(104) ? ((CollectionElementType)__pbn__TargetIdentifier.Object) : default;
            set => __pbn__TargetIdentifier = new global::ProtoBuf.DiscriminatedUnionObject(104, value);
        }
        public bool ShouldSerializeMacroIdentifier() => __pbn__TargetIdentifier.Is(104);
        public void ResetMacroIdentifier() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TargetIdentifier, 104);

        [global::ProtoBuf.ProtoMember(105, Name = @"prop_identifier")]
        public CollectionElementType PropIdentifier
        {
            get => __pbn__TargetIdentifier.Is(105) ? ((CollectionElementType)__pbn__TargetIdentifier.Object) : default;
            set => __pbn__TargetIdentifier = new global::ProtoBuf.DiscriminatedUnionObject(105, value);
        }
        public bool ShouldSerializePropIdentifier() => __pbn__TargetIdentifier.Is(105);
        public void ResetPropIdentifier() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TargetIdentifier, 105);

        [global::ProtoBuf.ProtoMember(106, Name = @"timer_identifier")]
        public CollectionElementType TimerIdentifier
        {
            get => __pbn__TargetIdentifier.Is(106) ? ((CollectionElementType)__pbn__TargetIdentifier.Object) : default;
            set => __pbn__TargetIdentifier = new global::ProtoBuf.DiscriminatedUnionObject(106, value);
        }
        public bool ShouldSerializeTimerIdentifier() => __pbn__TargetIdentifier.Is(106);
        public void ResetTimerIdentifier() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TargetIdentifier, 106);

        [global::ProtoBuf.ProtoContract()]
        public partial class ComputerKeyboard : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"key_equivalent")]
            [global::System.ComponentModel.DefaultValue("")]
            public string KeyEquivalent { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"key_equivalent_modifier_flags", IsPacked = true)]
            public global::System.Collections.Generic.List<ModifierFlags> KeyEquivalentModifierFlags { get; } = new global::System.Collections.Generic.List<ModifierFlags>();

            [global::ProtoBuf.ProtoContract()]
            public enum ModifierFlags
            {
                [global::ProtoBuf.ProtoEnum(Name = @"MODIFIERFLAGS_COMMAND_KEY")]
                ModifierflagsCommandKey = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"MODIFIERFLAGS_SHIFT_KEY")]
                ModifierflagsShiftKey = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"MODIFIERFLAGS_OPTION_KEY")]
                ModifierflagsOptionKey = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"MODIFIERFLAGS_CONTROL_KEY")]
                ModifierflagsControlKey = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"MODIFIERFLAGS_FUNCTION_KEY")]
                ModifierflagsFunctionKey = 4,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class MIDIKeyboard : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"channel")]
            public int Channel { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"pitch")]
            public int Pitch { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"velocity")]
            public int Velocity { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KeyMappingDocument : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"application_info")]
        public ApplicationInfo ApplicationInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"keymappings")]
        public global::System.Collections.Generic.List<KeyMapping> Keymappings { get; } = new global::System.Collections.Generic.List<KeyMapping>();

        [global::ProtoBuf.ProtoMember(3, Name = @"macos_keymappings")]
        public global::System.Collections.Generic.List<KeyMapping> MacosKeymappings { get; } = new global::System.Collections.Generic.List<KeyMapping>();

        [global::ProtoBuf.ProtoMember(4, Name = @"windows_keymappings")]
        public global::System.Collections.Generic.List<KeyMapping> WindowsKeymappings { get; } = new global::System.Collections.Generic.List<KeyMapping>();

    }

}


#endregion
