// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: liveVideoPlaylist.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LiveVideoPlaylist : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"actions")]
        public global::System.Collections.Generic.List<Action> Actions { get; } = new global::System.Collections.Generic.List<Action>();

        [global::ProtoBuf.ProtoMember(2, Name = @"targeted_layer_UUID")]
        public Uuid targetedlayerUUID { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"uuid")]
        public Uuid Uuid { get; set; }

    }

}


#endregion
