// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: messages.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Message : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Title { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"time_to_remove")]
        public double TimeToRemove { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"visible_on_network")]
        public bool VisibleOnNetwork { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"template")]
        public Template.Identification Template { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public ClearType clear_type { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"message_text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MessageText { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"tokens")]
        public global::System.Collections.Generic.List<Token> Tokens { get; } = new global::System.Collections.Generic.List<Token>();

        [global::ProtoBuf.ProtoMember(12, Name = @"token_values")]
        public global::System.Collections.Generic.List<TokenValue> TokenValues { get; } = new global::System.Collections.Generic.List<TokenValue>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Token : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
            public Uuid Uuid { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"text")]
            public TokenTypeText Text
            {
                get => __pbn__TokenType.Is(2) ? ((TokenTypeText)__pbn__TokenType.Object) : default;
                set => __pbn__TokenType = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
            }
            public bool ShouldSerializeText() => __pbn__TokenType.Is(2);
            public void ResetText() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TokenType, 2);

            private global::ProtoBuf.DiscriminatedUnionObject __pbn__TokenType;

            [global::ProtoBuf.ProtoMember(3, Name = @"timer")]
            public TokenTypeTimer Timer
            {
                get => __pbn__TokenType.Is(3) ? ((TokenTypeTimer)__pbn__TokenType.Object) : default;
                set => __pbn__TokenType = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
            }
            public bool ShouldSerializeTimer() => __pbn__TokenType.Is(3);
            public void ResetTimer() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TokenType, 3);

            [global::ProtoBuf.ProtoMember(4, Name = @"clock")]
            public TokenTypeClock Clock
            {
                get => __pbn__TokenType.Is(4) ? ((TokenTypeClock)__pbn__TokenType.Object) : default;
                set => __pbn__TokenType = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
            }
            public bool ShouldSerializeClock() => __pbn__TokenType.Is(4);
            public void ResetClock() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TokenType, 4);

            [global::ProtoBuf.ProtoContract()]
            public partial class TokenTypeText : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"name")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Name { get; set; } = "";

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class TokenTypeTimer : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"name")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Name { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2, Name = @"timer_uuid")]
                public Uuid TimerUuid { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class TokenTypeClock : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class TokenValue : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"token_id")]
            public Uuid TokenId { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"token_name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string TokenName { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"text")]
            public TokenValueText Text
            {
                get => __pbn__TokenValueType.Is(2) ? ((TokenValueText)__pbn__TokenValueType.Object) : default;
                set => __pbn__TokenValueType = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
            }
            public bool ShouldSerializeText() => __pbn__TokenValueType.Is(2);
            public void ResetText() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TokenValueType, 2);

            private global::ProtoBuf.DiscriminatedUnionObject __pbn__TokenValueType;

            [global::ProtoBuf.ProtoMember(3, Name = @"timer")]
            public TokenValueTimer Timer
            {
                get => __pbn__TokenValueType.Is(3) ? ((TokenValueTimer)__pbn__TokenValueType.Object) : default;
                set => __pbn__TokenValueType = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
            }
            public bool ShouldSerializeTimer() => __pbn__TokenValueType.Is(3);
            public void ResetTimer() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TokenValueType, 3);

            [global::ProtoBuf.ProtoMember(4, Name = @"clock")]
            public TokenValueClock Clock
            {
                get => __pbn__TokenValueType.Is(4) ? ((TokenValueClock)__pbn__TokenValueType.Object) : default;
                set => __pbn__TokenValueType = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
            }
            public bool ShouldSerializeClock() => __pbn__TokenValueType.Is(4);
            public void ResetClock() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TokenValueType, 4);

            [global::ProtoBuf.ProtoContract()]
            public partial class TokenValueText : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"value")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Value { get; set; } = "";

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class TokenValueTimer : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"configuration")]
                public Timer.Configuration Configuration { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"format")]
                public Timer.Format Format { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class TokenValueClock : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"format")]
                public Clock.Format Format { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum ClearType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CLEAR_TYPE_MANUAL")]
            ClearTypeManual = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CLEAR_TYPE_AFTER_TIME")]
            ClearTypeAfterTime = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CLEAR_TYPE_AFTER_TIMERS")]
            ClearTypeAfterTimers = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MessageDocument : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"application_info")]
        public ApplicationInfo ApplicationInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"messages")]
        public global::System.Collections.Generic.List<Message> Messages { get; } = new global::System.Collections.Generic.List<Message>();

    }

}


#endregion
