// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: planningCenter.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlanningCenterPlan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"plan_id_num")]
        public uint PlanIdNum { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"parent_id_num")]
        public uint ParentIdNum { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"series_title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SeriesTitle { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"plan_title")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlanTitle { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"date_list")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DateList { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"created_date")]
        public Timestamp CreatedDate { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"update_date")]
        public Timestamp UpdateDate { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"last_update_check_date")]
        public Timestamp LastUpdateCheckDate { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"plan_id_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlanIdStr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"parent_id_str")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ParentIdStr { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public partial class PlanItem : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"item_type")]
            public PlanItemType ItemType { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"pco_id_num")]
            public uint PcoIdNum { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"service_id_num")]
            public uint ServiceIdNum { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"parent_id_num")]
            public uint ParentIdNum { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(6, Name = @"attachments")]
            public global::System.Collections.Generic.List<Attachment> Attachments { get; } = new global::System.Collections.Generic.List<Attachment>();

            [global::ProtoBuf.ProtoMember(7, Name = @"update_date")]
            public Timestamp UpdateDate { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"linked_song")]
            public SongItem LinkedSong { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"pco_id_str")]
            [global::System.ComponentModel.DefaultValue("")]
            public string PcoIdStr { get; set; } = "";

            [global::ProtoBuf.ProtoMember(10, Name = @"service_id_str")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ServiceIdStr { get; set; } = "";

            [global::ProtoBuf.ProtoMember(11, Name = @"parent_id_str")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ParentIdStr { get; set; } = "";

            [global::ProtoBuf.ProtoContract()]
            public partial class Attachment : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"name")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Name { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2, Name = @"url")]
                public Url Url { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"created_date")]
                public Timestamp CreatedDate { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"linked_path")]
                public Url LinkedPath { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"pco_id_num")]
                public uint PcoIdNum { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"needs_update")]
                public bool NeedsUpdate { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"update_date")]
                public Timestamp UpdateDate { get; set; }

                [global::ProtoBuf.ProtoMember(8, Name = @"pco_id_str")]
                [global::System.ComponentModel.DefaultValue("")]
                public string PcoIdStr { get; set; } = "";

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class SongItem : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"pco_id_num")]
                public uint PcoIdNum { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"arrangement_id_num")]
                public uint ArrangementIdNum { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"ccli")]
                public Presentation.Ccli Ccli { get; set; }

                [global::ProtoBuf.ProtoMember(4)]
                public Sequence sequence { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"pco_id_str")]
                [global::System.ComponentModel.DefaultValue("")]
                public string PcoIdStr { get; set; } = "";

                [global::ProtoBuf.ProtoMember(6, Name = @"arrangement_id_str")]
                [global::System.ComponentModel.DefaultValue("")]
                public string ArrangementIdStr { get; set; } = "";

                [global::ProtoBuf.ProtoContract()]
                public partial class Sequence : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"pco_id_num")]
                    public uint PcoIdNum { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"name")]
                    [global::System.ComponentModel.DefaultValue("")]
                    public string Name { get; set; } = "";

                    [global::ProtoBuf.ProtoMember(3, Name = @"group_names")]
                    public global::System.Collections.Generic.List<string> GroupNames { get; } = new global::System.Collections.Generic.List<string>();

                    [global::ProtoBuf.ProtoMember(4, Name = @"pco_id_str")]
                    [global::System.ComponentModel.DefaultValue("")]
                    public string PcoIdStr { get; set; } = "";

                }

            }

            [global::ProtoBuf.ProtoContract()]
            public enum PlanItemType
            {
                [global::ProtoBuf.ProtoEnum(Name = @"PLAN_ITEM_TYPE_ITEM")]
                PlanItemTypeItem = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"PLAN_ITEM_TYPE_SONG")]
                PlanItemTypeSong = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"PLAN_ITEM_TYPE_MEDIA")]
                PlanItemTypeMedia = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"PLAN_ITEM_TYPE_HEADER")]
                PlanItemTypeHeader = 3,
            }

        }

    }

}


#endregion
