// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: playlist.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Playlist : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"expanded")]
        public bool Expanded { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"targeted_layer_uuid")]
        public Uuid TargetedLayerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"smart_directory_path")]
        public Url SmartDirectoryPath { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"hot_key")]
        public HotKey HotKey { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"cues")]
        public global::System.Collections.Generic.List<Cue> Cues { get; } = new global::System.Collections.Generic.List<Cue>();

        [global::ProtoBuf.ProtoMember(9, Name = @"children")]
        public global::System.Collections.Generic.List<Playlist> Childrens { get; } = new global::System.Collections.Generic.List<Playlist>();

        [global::ProtoBuf.ProtoMember(10, Name = @"timecode_enabled")]
        public bool TimecodeEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"timing")]
        public TimingType Timing { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public StartupInfo startup_info { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"playlists")]
        public PlaylistArray Playlists
        {
            get => __pbn__ChildrenType.Is(12) ? ((PlaylistArray)__pbn__ChildrenType.Object) : default;
            set => __pbn__ChildrenType = new global::ProtoBuf.DiscriminatedUnionObject(12, value);
        }
        public bool ShouldSerializePlaylists() => __pbn__ChildrenType.Is(12);
        public void ResetPlaylists() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ChildrenType, 12);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__ChildrenType;

        [global::ProtoBuf.ProtoMember(13, Name = @"items")]
        public PlaylistItems Items
        {
            get => __pbn__ChildrenType.Is(13) ? ((PlaylistItems)__pbn__ChildrenType.Object) : default;
            set => __pbn__ChildrenType = new global::ProtoBuf.DiscriminatedUnionObject(13, value);
        }
        public bool ShouldSerializeItems() => __pbn__ChildrenType.Is(13);
        public void ResetItems() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ChildrenType, 13);

        [global::ProtoBuf.ProtoMember(14, Name = @"smart_directory")]
        public FolderDirectory SmartDirectory
        {
            get => __pbn__LinkData.Is(14) ? ((FolderDirectory)__pbn__LinkData.Object) : default;
            set => __pbn__LinkData = new global::ProtoBuf.DiscriminatedUnionObject(14, value);
        }
        public bool ShouldSerializeSmartDirectory() => __pbn__LinkData.Is(14);
        public void ResetSmartDirectory() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__LinkData, 14);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__LinkData;

        [global::ProtoBuf.ProtoMember(15, Name = @"pco_plan")]
        public PlanningCenterPlan PcoPlan
        {
            get => __pbn__LinkData.Is(15) ? ((PlanningCenterPlan)__pbn__LinkData.Object) : default;
            set => __pbn__LinkData = new global::ProtoBuf.DiscriminatedUnionObject(15, value);
        }
        public bool ShouldSerializePcoPlan() => __pbn__LinkData.Is(15);
        public void ResetPcoPlan() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__LinkData, 15);

        [global::ProtoBuf.ProtoContract()]
        public partial class PlaylistArray : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"playlists")]
            public global::System.Collections.Generic.List<Playlist> Playlists { get; } = new global::System.Collections.Generic.List<Playlist>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class PlaylistItems : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"items")]
            public global::System.Collections.Generic.List<PlaylistItem> Items { get; } = new global::System.Collections.Generic.List<PlaylistItem>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class FolderDirectory : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"smart_directory")]
            public Url SmartDirectory { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public ImportBehavior import_behavior { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum ImportBehavior
            {
                [global::ProtoBuf.ProtoEnum(Name = @"IMPORT_BEHAVIOR_BACKGROUND")]
                ImportBehaviorBackground = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"IMPORT_BEHAVIOR_FOREGROUND")]
                ImportBehaviorForeground = 1,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Tag : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"color")]
            public Color Color { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"uuid")]
            public Uuid Uuid { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class StartupInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"trigger_on_startup")]
            public bool TriggerOnStartup { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_UNKNOWN")]
            TypeUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_PLAYLIST")]
            TypePlaylist = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_GROUP")]
            TypeGroup = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_SMART")]
            TypeSmart = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_ROOT")]
            TypeRoot = 4,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum TimingType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TIMING_TYPE_NONE")]
            TimingTypeNone = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TIMING_TYPE_TIMECODE")]
            TimingTypeTimecode = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TIMING_TYPE_TIME_OF_DAY")]
            TimingTypeTimeOfDay = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlaylistItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"tags")]
        public global::System.Collections.Generic.List<Uuid> Tags { get; } = new global::System.Collections.Generic.List<Uuid>();

        [global::ProtoBuf.ProtoMember(9, Name = @"is_hidden")]
        public bool IsHidden { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Header header
        {
            get => __pbn__ItemType.Is(3) ? ((Header)__pbn__ItemType.Object) : default;
            set => __pbn__ItemType = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeheader() => __pbn__ItemType.Is(3);
        public void Resetheader() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ItemType, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__ItemType;

        [global::ProtoBuf.ProtoMember(4)]
        public Presentation presentation
        {
            get => __pbn__ItemType.Is(4) ? ((Presentation)__pbn__ItemType.Object) : default;
            set => __pbn__ItemType = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializepresentation() => __pbn__ItemType.Is(4);
        public void Resetpresentation() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ItemType, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"cue")]
        public Cue Cue
        {
            get => __pbn__ItemType.Is(5) ? ((Cue)__pbn__ItemType.Object) : default;
            set => __pbn__ItemType = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeCue() => __pbn__ItemType.Is(5);
        public void ResetCue() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ItemType, 5);

        [global::ProtoBuf.ProtoMember(6)]
        public PlanningCenter planning_center
        {
            get => __pbn__ItemType.Is(6) ? ((PlanningCenter)__pbn__ItemType.Object) : default;
            set => __pbn__ItemType = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializeplanning_center() => __pbn__ItemType.Is(6);
        public void Resetplanning_center() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ItemType, 6);

        [global::ProtoBuf.ProtoMember(8)]
        public Placeholder placeholder
        {
            get => __pbn__ItemType.Is(8) ? ((Placeholder)__pbn__ItemType.Object) : default;
            set => __pbn__ItemType = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
        }
        public bool ShouldSerializeplaceholder() => __pbn__ItemType.Is(8);
        public void Resetplaceholder() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ItemType, 8);

        [global::ProtoBuf.ProtoContract()]
        public partial class Header : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"color")]
            public Color Color { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"actions")]
            public global::System.Collections.Generic.List<Action> Actions { get; } = new global::System.Collections.Generic.List<Action>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Presentation : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"document_path")]
            public Url DocumentPath { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"arrangement")]
            public Uuid Arrangement { get; set; }

            [global::ProtoBuf.ProtoMember(3)]
            public ContentDestination content_destination { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"user_music_key")]
            public MusicKeyScale UserMusicKey { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum ContentDestination
            {
                [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_DESTINATION_GLOBAL")]
                ContentDestinationGlobal = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_DESTINATION_ANNOUNCEMENTS")]
                ContentDestinationAnnouncements = 1,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class PlanningCenter : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"item")]
            public PlanningCenterPlan.PlanItem Item { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"linked_data")]
            public PlaylistItem LinkedData { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Placeholder : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"linked_data")]
            public PlaylistItem LinkedData { get; set; }

        }

    }

}


#endregion
