// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: presentationSlide.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PresentationSlide : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"base_slide")]
        public Slide BaseSlide { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Notes notes { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"template_guidelines")]
        public global::System.Collections.Generic.List<AlignmentGuide> TemplateGuidelines { get; } = new global::System.Collections.Generic.List<AlignmentGuide>();

        [global::ProtoBuf.ProtoMember(4, Name = @"chord_chart")]
        public Url ChordChart { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"transition")]
        public Transition Transition { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Notes : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"rtf_data")]
            public byte[] RtfData { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"attributes")]
            public Graphics.Text.Attributes Attributes { get; set; }

        }

    }

}


#endregion
