// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: presentation.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Presentation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"application_info")]
        public ApplicationInfo ApplicationInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"last_date_used")]
        public Timestamp LastDateUsed { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"last_modified_date")]
        public Timestamp LastModifiedDate { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"category")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Category { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"notes")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Notes { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"background")]
        public Background Background { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"chord_chart")]
        public Url ChordChart { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"selected_arrangement")]
        public Uuid SelectedArrangement { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"arrangements")]
        public global::System.Collections.Generic.List<Arrangement> Arrangements { get; } = new global::System.Collections.Generic.List<Arrangement>();

        [global::ProtoBuf.ProtoMember(12, Name = @"cue_groups")]
        public global::System.Collections.Generic.List<CueGroup> CueGroups { get; } = new global::System.Collections.Generic.List<CueGroup>();

        [global::ProtoBuf.ProtoMember(13, Name = @"cues")]
        public global::System.Collections.Generic.List<Cue> Cues { get; } = new global::System.Collections.Generic.List<Cue>();

        [global::ProtoBuf.ProtoMember(14)]
        public Ccli ccli { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public BibleReference bible_reference { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public SocialMedia social_media { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public Timeline timeline { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"transition")]
        public Transition Transition { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public ContentDestination content_destination { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public MultiTracksLicensing multi_tracks_licensing { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"music_key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string MusicKey { get; set; } = "";

        [global::ProtoBuf.ProtoMember(23)]
        public Music music { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"slide_show_duration")]
        public double SlideShowDuration
        {
            get => __pbn__SlideShow.Is(20) ? __pbn__SlideShow.Double : default;
            set => __pbn__SlideShow = new global::ProtoBuf.DiscriminatedUnion64(20, value);
        }
        public bool ShouldSerializeSlideShowDuration() => __pbn__SlideShow.Is(20);
        public void ResetSlideShowDuration() => global::ProtoBuf.DiscriminatedUnion64.Reset(ref __pbn__SlideShow, 20);

        private global::ProtoBuf.DiscriminatedUnion64 __pbn__SlideShow;

        [global::ProtoBuf.ProtoContract(Name = @"CCLI")]
        public partial class Ccli : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"author")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Author { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"artist_credits")]
            [global::System.ComponentModel.DefaultValue("")]
            public string ArtistCredits { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"song_title")]
            [global::System.ComponentModel.DefaultValue("")]
            public string SongTitle { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4, Name = @"publisher")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Publisher { get; set; } = "";

            [global::ProtoBuf.ProtoMember(5, Name = @"copyright_year")]
            public uint CopyrightYear { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"song_number")]
            public uint SongNumber { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"display")]
            public bool Display { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"album")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Album { get; set; } = "";

            [global::ProtoBuf.ProtoMember(9, Name = @"artwork")]
            public byte[] Artwork { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class BibleReference : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"book_index")]
            public uint BookIndex { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"book_name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string BookName { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"chapter_range")]
            public IntRange ChapterRange { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"verse_range")]
            public IntRange VerseRange { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"translation_name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string TranslationName { get; set; } = "";

            [global::ProtoBuf.ProtoMember(6, Name = @"translation_display_abbreviation")]
            [global::System.ComponentModel.DefaultValue("")]
            public string TranslationDisplayAbbreviation { get; set; } = "";

            [global::ProtoBuf.ProtoMember(7, Name = @"translation_internal_abbreviation")]
            [global::System.ComponentModel.DefaultValue("")]
            public string TranslationInternalAbbreviation { get; set; } = "";

            [global::ProtoBuf.ProtoMember(8, Name = @"book_key")]
            [global::System.ComponentModel.DefaultValue("")]
            public string BookKey { get; set; } = "";

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SocialMedia : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"term")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Term { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"time")]
            public Timestamp Time { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Timeline : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"cues")]
            public global::System.Collections.Generic.List<Cue> Cues { get; } = new global::System.Collections.Generic.List<Cue>();

            [global::ProtoBuf.ProtoMember(5, Name = @"duration")]
            public double Duration { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"loop")]
            public bool Loop { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"audio_action")]
            public Action AudioAction { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"timecode_enable")]
            public bool TimecodeEnable { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"timecode_offset")]
            public double TimecodeOffset { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class Cue : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"trigger_time")]
                public double TriggerTime { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"name")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Name { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2, Name = @"cue_id")]
                public Uuid CueId
                {
                    get => __pbn__trigger_info.Is(2) ? ((Uuid)__pbn__trigger_info.Object) : default;
                    set => __pbn__trigger_info = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
                }
                public bool ShouldSerializeCueId() => __pbn__trigger_info.Is(2);
                public void ResetCueId() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__trigger_info, 2);

                private global::ProtoBuf.DiscriminatedUnionObject __pbn__trigger_info;

                [global::ProtoBuf.ProtoMember(4, Name = @"media_action")]
                public Action MediaAction
                {
                    get => __pbn__trigger_info.Is(4) ? ((Action)__pbn__trigger_info.Object) : default;
                    set => __pbn__trigger_info = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
                }
                public bool ShouldSerializeMediaAction() => __pbn__trigger_info.Is(4);
                public void ResetMediaAction() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__trigger_info, 4);

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Arrangement : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
            public Uuid Uuid { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"group_identifiers")]
            public global::System.Collections.Generic.List<Uuid> GroupIdentifiers { get; } = new global::System.Collections.Generic.List<Uuid>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class CueGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"group")]
            public Group Group { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"cue_identifiers")]
            public global::System.Collections.Generic.List<Uuid> CueIdentifiers { get; } = new global::System.Collections.Generic.List<Uuid>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class MultiTracksLicensing : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"song_identifier")]
            public long SongIdentifier { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"customer_identifier")]
            [global::System.ComponentModel.DefaultValue("")]
            public string CustomerIdentifier { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"expiration_date")]
            public Timestamp ExpirationDate { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"license_expiration")]
            public Timestamp LicenseExpiration { get; set; }

            [global::ProtoBuf.ProtoMember(5)]
            public Subscription subscription { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum Subscription
            {
                [global::ProtoBuf.ProtoEnum(Name = @"SUBSCRIPTION_CHART_PRO")]
                SubscriptionChartPro = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"SUBSCRIPTION_SLIDE_PRO")]
                SubscriptionSlidePro = 1,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Music : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"original_music_key")]
            [global::System.ComponentModel.DefaultValue("")]
            public string OriginalMusicKey { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"user_music_key")]
            [global::System.ComponentModel.DefaultValue("")]
            public string UserMusicKey { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"original")]
            public MusicKeyScale Original { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"user")]
            public MusicKeyScale User { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum ContentDestination
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_DESTINATION_GLOBAL")]
            ContentDestinationGlobal = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_DESTINATION_ANNOUNCEMENTS")]
            ContentDestinationAnnouncements = 1,
        }

    }

}


#endregion
