// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: proAudienceLook.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ProAudienceLook : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"screen_looks")]
        public global::System.Collections.Generic.List<ProScreenLook> ScreenLooks { get; } = new global::System.Collections.Generic.List<ProScreenLook>();

        [global::ProtoBuf.ProtoMember(4, Name = @"original_look_uuid")]
        public Uuid OriginalLookUuid { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class ProScreenLook : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"pro_screen_uuid")]
            public Uuid ProScreenUuid { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"props_enabled")]
            public bool PropsEnabled { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"live_video_enabled")]
            public bool LiveVideoEnabled { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"presentation_background_enabled")]
            public bool PresentationBackgroundEnabled { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"template_document_file_path")]
            public Url TemplateDocumentFilePath { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"template_slide_uuid")]
            public Uuid TemplateSlideUuid { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"presentation_foreground_enabled")]
            public bool PresentationForegroundEnabled { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"mask_uuid")]
            public Uuid MaskUuid { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"announcements_enabled")]
            public bool AnnouncementsEnabled { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"props_layer_enabled")]
            public bool PropsLayerEnabled { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"messages_layer_enabled")]
            public bool MessagesLayerEnabled { get; set; }

        }

    }

}


#endregion
