// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: proApiV1BasicTypes.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Identifier")]
    public partial class APIv1Identifier : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uuid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"index")]
        public uint Index { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_SlideIndex")]
    public partial class APIv1SlideIndex : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"index")]
        public uint Index { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"presentation_id")]
        public APIv1Identifier PresentationId { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Playlist")]
    public partial class APIv1Playlist : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public APIv1PlaylistType Type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"children")]
        public global::System.Collections.Generic.List<APIv1Playlist> Childrens { get; } = new global::System.Collections.Generic.List<APIv1Playlist>();

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_PlaylistType")]
        public enum APIv1PlaylistType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"group")]
            Group = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"playlist")]
            Playlist = 1,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_PlaylistAndItem")]
    public partial class APIv1PlaylistAndItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"playlist")]
        public APIv1Identifier Playlist { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"item")]
        public APIv1Identifier Item { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_MediaPlaylistItem")]
    public partial class APIv1MediaPlaylistItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public APIv1MediaPlaylistItemType Type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"artist")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Artist { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"duration")]
        public uint Duration { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_MediaPlaylistItemType")]
        public enum APIv1MediaPlaylistItemType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"audio")]
            Audio = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"image")]
            Image = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"video")]
            Video = 2,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_PlaylistItem")]
    public partial class APIv1PlaylistItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        public APIv1PlaylistItemType Type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"is_hidden")]
        public bool IsHidden { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"is_pco")]
        public bool IsPco { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"header_color")]
        public APIv1Color HeaderColor { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"duration")]
        public global::Google.Protobuf.WellKnownTypes.UInt32Value Duration { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_PlaylistItemType")]
        public enum APIv1PlaylistItemType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"presentation")]
            Presentation = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"placeholder")]
            Placeholder = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"header")]
            Header = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"media")]
            Media = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"audio")]
            Audio = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"livevideo")]
            Livevideo = 5,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_ClearGroup")]
    public partial class APIv1ClearGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"icon")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Icon { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"tint")]
        public APIv1Color Tint { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"layers", IsPacked = true)]
        public global::System.Collections.Generic.List<APIv1ClearGroupLayerType> Layers { get; } = new global::System.Collections.Generic.List<APIv1ClearGroupLayerType>();

        [global::ProtoBuf.ProtoMember(5, Name = @"stop_timeline_announcements")]
        public bool StopTimelineAnnouncements { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"stop_timeline_presentation")]
        public bool StopTimelinePresentation { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"clear_next_presentation")]
        public bool ClearNextPresentation { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_ClearGroupLayerType")]
        public enum APIv1ClearGroupLayerType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"music")]
            Music = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"audio_effects")]
            AudioEffects = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"props")]
            Props = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"messages")]
            Messages = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"announcements")]
            Announcements = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"presentation")]
            Presentation = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"presentation_media")]
            PresentationMedia = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"video_input")]
            VideoInput = 7,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Message")]
    public partial class APIv1Message : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"tokens")]
        public global::System.Collections.Generic.List<APIv1MessageToken> Tokens { get; } = new global::System.Collections.Generic.List<APIv1MessageToken>();

        [global::ProtoBuf.ProtoMember(4, Name = @"theme")]
        public APIv1Identifier Theme { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_MessageToken")]
        public partial class APIv1MessageToken : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"text")]
            public APIv1TextToken Text
            {
                get => __pbn__TokenType.Is(2) ? ((APIv1TextToken)__pbn__TokenType.Object) : default;
                set => __pbn__TokenType = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
            }
            public bool ShouldSerializeText() => __pbn__TokenType.Is(2);
            public void ResetText() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TokenType, 2);

            private global::ProtoBuf.DiscriminatedUnionObject __pbn__TokenType;

            [global::ProtoBuf.ProtoMember(3, Name = @"timer")]
            public APIv1TimerToken Timer
            {
                get => __pbn__TokenType.Is(3) ? ((APIv1TimerToken)__pbn__TokenType.Object) : default;
                set => __pbn__TokenType = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
            }
            public bool ShouldSerializeTimer() => __pbn__TokenType.Is(3);
            public void ResetTimer() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TokenType, 3);

            [global::ProtoBuf.ProtoMember(4, Name = @"clock")]
            public APIv1ClockToken Clock
            {
                get => __pbn__TokenType.Is(4) ? ((APIv1ClockToken)__pbn__TokenType.Object) : default;
                set => __pbn__TokenType = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
            }
            public bool ShouldSerializeClock() => __pbn__TokenType.Is(4);
            public void ResetClock() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TokenType, 4);

            [global::ProtoBuf.ProtoContract(Name = @"API_v1_TextToken")]
            public partial class APIv1TextToken : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"text")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Text { get; set; } = "";

            }

            [global::ProtoBuf.ProtoContract(Name = @"API_v1_TimerToken")]
            public partial class APIv1TimerToken : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"id")]
                public APIv1Identifier Id { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"allows_overrun")]
                public bool AllowsOverrun { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"format")]
                public APIv1TimerFormat Format { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"countdown")]
                public APIv1Timer.APIv1TimerCountdown Countdown
                {
                    get => __pbn__TimerConfiguration.Is(3) ? ((APIv1Timer.APIv1TimerCountdown)__pbn__TimerConfiguration.Object) : default;
                    set => __pbn__TimerConfiguration = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
                }
                public bool ShouldSerializeCountdown() => __pbn__TimerConfiguration.Is(3);
                public void ResetCountdown() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TimerConfiguration, 3);

                private global::ProtoBuf.DiscriminatedUnionObject __pbn__TimerConfiguration;

                [global::ProtoBuf.ProtoMember(4, Name = @"count_down_to_time")]
                public APIv1Timer.APIv1TimerCountdownToTime CountDownToTime
                {
                    get => __pbn__TimerConfiguration.Is(4) ? ((APIv1Timer.APIv1TimerCountdownToTime)__pbn__TimerConfiguration.Object) : default;
                    set => __pbn__TimerConfiguration = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
                }
                public bool ShouldSerializeCountDownToTime() => __pbn__TimerConfiguration.Is(4);
                public void ResetCountDownToTime() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TimerConfiguration, 4);

                [global::ProtoBuf.ProtoMember(5, Name = @"elapsed")]
                public APIv1Timer.APIv1TimerElapsed Elapsed
                {
                    get => __pbn__TimerConfiguration.Is(5) ? ((APIv1Timer.APIv1TimerElapsed)__pbn__TimerConfiguration.Object) : default;
                    set => __pbn__TimerConfiguration = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
                }
                public bool ShouldSerializeElapsed() => __pbn__TimerConfiguration.Is(5);
                public void ResetElapsed() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TimerConfiguration, 5);

            }

            [global::ProtoBuf.ProtoContract(Name = @"API_v1_ClockToken")]
            public partial class APIv1ClockToken : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"date")]
                public APIv1ClockTokenFormat Date { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"time")]
                public APIv1ClockTokenFormat Time { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"is_24_hours")]
                public bool Is24Hours { get; set; }

                [global::ProtoBuf.ProtoContract(Name = @"API_v1_ClockTokenFormat")]
                public enum APIv1ClockTokenFormat
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"none")]
                    None = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"short")]
                    Short = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"medium")]
                    Medium = 2,
                    [global::ProtoBuf.ProtoEnum(Name = @"long")]
                    Long = 3,
                    [global::ProtoBuf.ProtoEnum(Name = @"full")]
                    Full = 4,
                }

            }

        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Timer")]
    public partial class APIv1Timer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"allows_overrun")]
        public bool AllowsOverrun { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"countdown")]
        public APIv1TimerCountdown Countdown
        {
            get => __pbn__TimerConfiguration.Is(3) ? ((APIv1TimerCountdown)__pbn__TimerConfiguration.Object) : default;
            set => __pbn__TimerConfiguration = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeCountdown() => __pbn__TimerConfiguration.Is(3);
        public void ResetCountdown() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TimerConfiguration, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__TimerConfiguration;

        [global::ProtoBuf.ProtoMember(4, Name = @"count_down_to_time")]
        public APIv1TimerCountdownToTime CountDownToTime
        {
            get => __pbn__TimerConfiguration.Is(4) ? ((APIv1TimerCountdownToTime)__pbn__TimerConfiguration.Object) : default;
            set => __pbn__TimerConfiguration = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeCountDownToTime() => __pbn__TimerConfiguration.Is(4);
        public void ResetCountDownToTime() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TimerConfiguration, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"elapsed")]
        public APIv1TimerElapsed Elapsed
        {
            get => __pbn__TimerConfiguration.Is(5) ? ((APIv1TimerElapsed)__pbn__TimerConfiguration.Object) : default;
            set => __pbn__TimerConfiguration = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeElapsed() => __pbn__TimerConfiguration.Is(5);
        public void ResetElapsed() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TimerConfiguration, 5);

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_Timer_Countdown")]
        public partial class APIv1TimerCountdown : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"duration")]
            public int Duration { get; set; }

        }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_Timer_CountdownToTime")]
        public partial class APIv1TimerCountdownToTime : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"time_of_day")]
            public int TimeOfDay { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"period")]
            public APIv1TimePeriod Period { get; set; }

            [global::ProtoBuf.ProtoContract(Name = @"API_v1_TimePeriod")]
            public enum APIv1TimePeriod
            {
                [global::ProtoBuf.ProtoEnum(Name = @"am")]
                Am = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"pm")]
                Pm = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"is_24_hour")]
                Is24Hour = 2,
            }

        }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_Timer_Elapsed")]
        public partial class APIv1TimerElapsed : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"start_time")]
            public int StartTime { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"end_time")]
            public int EndTime { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"has_end_time")]
            public bool HasEndTime { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_TimerFormat")]
    public partial class APIv1TimerFormat : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(6, Name = @"hour")]
        public APIv1TimerUnitDisplayFormat Hour { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"minute")]
        public APIv1TimerUnitDisplayFormat Minute { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"second")]
        public APIv1TimerUnitDisplayFormat Second { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"millisecond")]
        public APIv1TimerUnitDisplayFormat Millisecond { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_TimerUnitDisplayFormat")]
        public enum APIv1TimerUnitDisplayFormat
        {
            [global::ProtoBuf.ProtoEnum(Name = @"none")]
            None = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"short")]
            Short = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"long")]
            Long = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"remove_short")]
            RemoveShort = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"remove_long")]
            RemoveLong = 4,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_TimerValue")]
    public partial class APIv1TimerValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Time { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"state")]
        public APIv1TimerState State { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_TimerState")]
        public enum APIv1TimerState
        {
            [global::ProtoBuf.ProtoEnum(Name = @"stopped")]
            Stopped = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"running")]
            Running = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"complete")]
            Complete = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"overrunning")]
            Overrunning = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"overran")]
            Overran = 4,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Color")]
    public partial class APIv1Color : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"red")]
        public double Red { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"green")]
        public double Green { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"blue")]
        public double Blue { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"alpha")]
        public double Alpha { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Look")]
    public partial class APIv1Look : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"screens")]
        public global::System.Collections.Generic.List<APIv1Screen> Screens { get; } = new global::System.Collections.Generic.List<APIv1Screen>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Screen")]
    public partial class APIv1Screen : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"video_input")]
        public bool VideoInput { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"media")]
        public bool Media { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"slide")]
        public bool Slide { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"announcements")]
        public bool Announcements { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"props")]
        public bool Props { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"messages")]
        public bool Messages { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"presentation")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Presentation { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"mask")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Mask { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Macro")]
    public partial class APIv1Macro : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"color")]
        public APIv1Color Color { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_GroupMember")]
    public partial class APIv1GroupMember : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ip { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"port")]
        public uint Port { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_GroupMemberStatus")]
    public partial class APIv1GroupMemberStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ip")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ip { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"port")]
        public uint Port { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"platform")]
        public APIv1GroupMemberStatusPlatform Platform { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"os_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OsVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"host_description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string HostDescription { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"api_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ApiVersion { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"connection_status")]
        public APIv1GroupMemberStatusConnectionStatus ConnectionStatus { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_GroupMemberStatus_Platform")]
        public enum APIv1GroupMemberStatusPlatform
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_UNKNOWN")]
            PlatformUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_MACOS")]
            PlatformMacos = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_WIN32")]
            PlatformWin32 = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"PLATFORM_WEB")]
            PlatformWeb = 3,
        }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_GroupMemberStatus_ConnectionStatus")]
        public enum APIv1GroupMemberStatusConnectionStatus
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CONNECTION_STATUS_UNKNOWN")]
            ConnectionStatusUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CONNECTION_STATUS_CONNECTED")]
            ConnectionStatusConnected = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CONNECTION_STATUS_DISCONNECTED")]
            ConnectionStatusDisconnected = 2,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_GroupDefinition")]
    public partial class APIv1GroupDefinition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"timestamp")]
        public Timestamp Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"secret")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Secret { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"members")]
        public global::System.Collections.Generic.List<APIv1GroupMember> Members { get; } = new global::System.Collections.Generic.List<APIv1GroupMember>();

        [global::ProtoBuf.ProtoMember(5, Name = @"group_identifier")]
        public Uuid GroupIdentifier { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Error_Response")]
    public partial class APIv1ErrorResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error")]
        public APIv1ErrorType Error { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_Error_Type")]
        public enum APIv1ErrorType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NOT_FOUND")]
            NotFound = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"BAD_REQUEST")]
            BadRequest = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"INTERNAL_ERROR")]
            InternalError = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"UNAUTHORIZED")]
            Unauthorized = 3,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_CaptureSettings")]
    public partial class APIv1CaptureSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"source")]
        public Uuid Source { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"audio_routing")]
        public global::System.Collections.Generic.List<APIv1AudioRouting> AudioRoutings { get; } = new global::System.Collections.Generic.List<APIv1AudioRouting>();

        [global::ProtoBuf.ProtoMember(3, Name = @"disk")]
        public APIv1DiskCapture Disk
        {
            get => __pbn__Destination.Is(3) ? ((APIv1DiskCapture)__pbn__Destination.Object) : default;
            set => __pbn__Destination = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeDisk() => __pbn__Destination.Is(3);
        public void ResetDisk() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Destination, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__Destination;

        [global::ProtoBuf.ProtoMember(4, Name = @"rtmp")]
        public APIv1RTMPCapture Rtmp
        {
            get => __pbn__Destination.Is(4) ? ((APIv1RTMPCapture)__pbn__Destination.Object) : default;
            set => __pbn__Destination = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeRtmp() => __pbn__Destination.Is(4);
        public void ResetRtmp() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Destination, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"resi")]
        public APIv1ResiCapture Resi
        {
            get => __pbn__Destination.Is(5) ? ((APIv1ResiCapture)__pbn__Destination.Object) : default;
            set => __pbn__Destination = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeResi() => __pbn__Destination.Is(5);
        public void ResetResi() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Destination, 5);

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Size")]
    public partial class APIv1Size : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"width")]
        public uint Width { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"height")]
        public uint Height { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_AudioRouting")]
    public partial class APIv1AudioRouting : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"map", IsPacked = true)]
        public uint[] Maps { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_DiskCapture")]
    public partial class APIv1DiskCapture : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"file_location")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FileLocation { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"codec")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Codec { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"resolution")]
        public APIv1Size Resolution { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"frame_rate")]
        public double FrameRate { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_RTMPCapture")]
    public partial class APIv1RTMPCapture : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"server")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Server { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"encoding")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Encoding { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"save_local")]
        public bool SaveLocal { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"file_location")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FileLocation { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_ResiCapture")]
    public partial class APIv1ResiCapture : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EventName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"event_description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EventDescription { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"destination_group")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DestinationGroup { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"encoding")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Encoding { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Presentation")]
    public partial class APIv1Presentation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"groups")]
        public global::System.Collections.Generic.List<SlideGroup> Groups { get; } = new global::System.Collections.Generic.List<SlideGroup>();

        [global::ProtoBuf.ProtoMember(3, Name = @"has_timeline")]
        public bool HasTimeline { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"presentation_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PresentationPath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        public Destination destination { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class SlideGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"color")]
            public APIv1Color Color { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"slides")]
            public global::System.Collections.Generic.List<Slide> Slides { get; } = new global::System.Collections.Generic.List<Slide>();

            [global::ProtoBuf.ProtoContract()]
            public partial class Slide : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"enabled")]
                public bool Enabled { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"notes")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Notes { get; set; } = "";

                [global::ProtoBuf.ProtoMember(3, Name = @"text")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Text { get; set; } = "";

                [global::ProtoBuf.ProtoMember(5, Name = @"label")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Label { get; set; } = "";

                [global::ProtoBuf.ProtoMember(6, Name = @"size")]
                public APIv1Size Size { get; set; }

            }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Destination
        {
            [global::ProtoBuf.ProtoEnum(Name = @"presentation")]
            Presentation = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"announcements")]
            Announcements = 1,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_StageLayoutMap")]
    public partial class APIv1StageLayoutMap : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entries")]
        public global::System.Collections.Generic.List<Entry> Entries { get; } = new global::System.Collections.Generic.List<Entry>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Entry : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"screen")]
            public APIv1Identifier Screen { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"layout")]
            public APIv1Identifier Layout { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_ThemeGroup")]
    public partial class APIv1ThemeGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"groups")]
        public global::System.Collections.Generic.List<APIv1ThemeGroup> Groups { get; } = new global::System.Collections.Generic.List<APIv1ThemeGroup>();

        [global::ProtoBuf.ProtoMember(3, Name = @"themes")]
        public global::System.Collections.Generic.List<APIv1Theme> Themes { get; } = new global::System.Collections.Generic.List<APIv1Theme>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_Theme")]
    public partial class APIv1Theme : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"slides")]
        public global::System.Collections.Generic.List<APIv1ThemeSlide> Slides { get; } = new global::System.Collections.Generic.List<APIv1ThemeSlide>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_ThemeSlide")]
    public partial class APIv1ThemeSlide : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"size")]
        public APIv1Size Size { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"background")]
        public APIv1Color Background { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_SlideDisplayDetails")]
    public partial class APIv1SlideDisplayDetails : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Text { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"notes")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Notes { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uuid { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_ScreenConfig")]
    public partial class APIv1ScreenConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"size")]
        public APIv1Size Size { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"screen_type")]
        public APIv1ScreenType ScreenType { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"API_v1_ScreenType")]
        public enum APIv1ScreenType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"audience")]
            Audience = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"stage")]
            Stage = 1,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"API_v1_PropData")]
    public partial class APIv1PropData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public APIv1Identifier Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"is_active")]
        public bool IsActive { get; set; }

    }

}


#endregion
