// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: proCore.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MediaMetadataRequestInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"file_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FilePath { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"time")]
        public float Time { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"width")]
        public uint Width { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"height")]
        public uint Height { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"effects")]
        public global::System.Collections.Generic.List<Effect> Effects { get; } = new global::System.Collections.Generic.List<Effect>();

        [global::ProtoBuf.ProtoMember(6, Name = @"crop_insets")]
        public Graphics.EdgeInsets CropInsets { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"native_rotation")]
        public NativeRotationType NativeRotation { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"flipped_horizontally")]
        public bool FlippedHorizontally { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"flipped_vertically")]
        public bool FlippedVertically { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum NativeRotationType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_STANDARD")]
            NativeRotationTypeRotateStandard = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_90")]
            NativeRotationTypeRotate90 = 90,
            [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_180")]
            NativeRotationTypeRotate180 = 180,
            [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_270")]
            NativeRotationTypeRotate270 = 270,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MediaMetadataRequestResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Metadata metadata { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"generated_bitmap_info")]
        public BitmapInfo GeneratedBitmapInfo { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Metadata : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"width")]
            public uint Width { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"height")]
            public uint Height { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"fps")]
            public float Fps { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"duration")]
            public float Duration { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"number_audio_channels")]
            public uint NumberAudioChannels { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"codec")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Codec { get; set; } = "";

            [global::ProtoBuf.ProtoMember(7, Name = @"artist")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Artist { get; set; } = "";

            [global::ProtoBuf.ProtoMember(8, Name = @"title")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Title { get; set; } = "";

            [global::ProtoBuf.ProtoMember(9, Name = @"rotation")]
            public float Rotation { get; set; }

            [global::ProtoBuf.ProtoMember(10)]
            public ContentType content_type { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum ContentType
            {
                [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_TYPE_UNKNOWN")]
                ContentTypeUnknown = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_TYPE_AUDIO")]
                ContentTypeAudio = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_TYPE_IMAGE")]
                ContentTypeImage = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_TYPE_VIDEO")]
                ContentTypeVideo = 3,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class BitmapInfo : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"width")]
            public uint Width { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"height")]
            public uint Height { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TriggerOptions : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ContentDestination content_destination { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool suppressAutoStartVideo { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool suppressMediaBackground { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool forceRetrigger { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool resetChordChart { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool fromPlaylistLibrary { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool fromTimeline { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"ignore_analytics")]
        public bool IgnoreAnalytics { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ContentDestination
        {
            [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_DESTINATION_GLOBAL")]
            ContentDestinationGlobal = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"CONTENT_DESTINATION_ANNOUNCEMENTS")]
            ContentDestinationAnnouncements = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ControlTransport : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"play")]
        public PlayControlType Play
        {
            get => __pbn__ControlType.Is(1) ? ((PlayControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializePlay() => __pbn__ControlType.Is(1);
        public void ResetPlay() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__ControlType;

        [global::ProtoBuf.ProtoMember(2, Name = @"pause")]
        public PauseControlType Pause
        {
            get => __pbn__ControlType.Is(2) ? ((PauseControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializePause() => __pbn__ControlType.Is(2);
        public void ResetPause() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"rewind")]
        public RewindControlType Rewind
        {
            get => __pbn__ControlType.Is(3) ? ((RewindControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeRewind() => __pbn__ControlType.Is(3);
        public void ResetRewind() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"fastforward")]
        public FastForwardControlType Fastforward
        {
            get => __pbn__ControlType.Is(4) ? ((FastForwardControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeFastforward() => __pbn__ControlType.Is(4);
        public void ResetFastforward() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"skip_back")]
        public SkipBackControlType SkipBack
        {
            get => __pbn__ControlType.Is(5) ? ((SkipBackControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeSkipBack() => __pbn__ControlType.Is(5);
        public void ResetSkipBack() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"skip_forward")]
        public SkipForwardControlType SkipForward
        {
            get => __pbn__ControlType.Is(6) ? ((SkipForwardControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializeSkipForward() => __pbn__ControlType.Is(6);
        public void ResetSkipForward() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"step_back")]
        public StepBackControlType StepBack
        {
            get => __pbn__ControlType.Is(7) ? ((StepBackControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
        }
        public bool ShouldSerializeStepBack() => __pbn__ControlType.Is(7);
        public void ResetStepBack() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 7);

        [global::ProtoBuf.ProtoMember(8, Name = @"step_forward")]
        public StepForwardControlType StepForward
        {
            get => __pbn__ControlType.Is(8) ? ((StepForwardControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(8, value);
        }
        public bool ShouldSerializeStepForward() => __pbn__ControlType.Is(8);
        public void ResetStepForward() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 8);

        [global::ProtoBuf.ProtoMember(9, Name = @"go_to_start")]
        public GoToStartControlType GoToStart
        {
            get => __pbn__ControlType.Is(9) ? ((GoToStartControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(9, value);
        }
        public bool ShouldSerializeGoToStart() => __pbn__ControlType.Is(9);
        public void ResetGoToStart() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 9);

        [global::ProtoBuf.ProtoMember(10, Name = @"go_to_end")]
        public GoToEndControlType GoToEnd
        {
            get => __pbn__ControlType.Is(10) ? ((GoToEndControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(10, value);
        }
        public bool ShouldSerializeGoToEnd() => __pbn__ControlType.Is(10);
        public void ResetGoToEnd() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 10);

        [global::ProtoBuf.ProtoMember(11, Name = @"jump_to_time")]
        public JumpToTimeControlType JumpToTime
        {
            get => __pbn__ControlType.Is(11) ? ((JumpToTimeControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(11, value);
        }
        public bool ShouldSerializeJumpToTime() => __pbn__ControlType.Is(11);
        public void ResetJumpToTime() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 11);

        [global::ProtoBuf.ProtoMember(12, Name = @"jump_to_percent")]
        public JumpToPercentControlType JumpToPercent
        {
            get => __pbn__ControlType.Is(12) ? ((JumpToPercentControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(12, value);
        }
        public bool ShouldSerializeJumpToPercent() => __pbn__ControlType.Is(12);
        public void ResetJumpToPercent() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 12);

        [global::ProtoBuf.ProtoMember(13, Name = @"mark_in")]
        public MarkInPointControlType MarkIn
        {
            get => __pbn__ControlType.Is(13) ? ((MarkInPointControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(13, value);
        }
        public bool ShouldSerializeMarkIn() => __pbn__ControlType.Is(13);
        public void ResetMarkIn() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 13);

        [global::ProtoBuf.ProtoMember(14, Name = @"mark_out")]
        public MarkOutPointControlType MarkOut
        {
            get => __pbn__ControlType.Is(14) ? ((MarkOutPointControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(14, value);
        }
        public bool ShouldSerializeMarkOut() => __pbn__ControlType.Is(14);
        public void ResetMarkOut() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 14);

        [global::ProtoBuf.ProtoMember(15, Name = @"set_scale_mode")]
        public SetScaleModeControlType SetScaleMode
        {
            get => __pbn__ControlType.Is(15) ? ((SetScaleModeControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(15, value);
        }
        public bool ShouldSerializeSetScaleMode() => __pbn__ControlType.Is(15);
        public void ResetSetScaleMode() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 15);

        [global::ProtoBuf.ProtoMember(16, Name = @"set_flipped_mode")]
        public SetFlippedModeControlType SetFlippedMode
        {
            get => __pbn__ControlType.Is(16) ? ((SetFlippedModeControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(16, value);
        }
        public bool ShouldSerializeSetFlippedMode() => __pbn__ControlType.Is(16);
        public void ResetSetFlippedMode() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 16);

        [global::ProtoBuf.ProtoMember(17, Name = @"set_play_rate")]
        public SetPlayRateControlType SetPlayRate
        {
            get => __pbn__ControlType.Is(17) ? ((SetPlayRateControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(17, value);
        }
        public bool ShouldSerializeSetPlayRate() => __pbn__ControlType.Is(17);
        public void ResetSetPlayRate() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 17);

        [global::ProtoBuf.ProtoMember(18, Name = @"set_rotation")]
        public SetNativeRotationControlType SetRotation
        {
            get => __pbn__ControlType.Is(18) ? ((SetNativeRotationControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(18, value);
        }
        public bool ShouldSerializeSetRotation() => __pbn__ControlType.Is(18);
        public void ResetSetRotation() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 18);

        [global::ProtoBuf.ProtoMember(19, Name = @"toggle_playback")]
        public TogglePlaybackControlType TogglePlayback
        {
            get => __pbn__ControlType.Is(19) ? ((TogglePlaybackControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(19, value);
        }
        public bool ShouldSerializeTogglePlayback() => __pbn__ControlType.Is(19);
        public void ResetTogglePlayback() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 19);

        [global::ProtoBuf.ProtoMember(20, Name = @"set_effects")]
        public SetEffectsControlType SetEffects
        {
            get => __pbn__ControlType.Is(20) ? ((SetEffectsControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(20, value);
        }
        public bool ShouldSerializeSetEffects() => __pbn__ControlType.Is(20);
        public void ResetSetEffects() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 20);

        [global::ProtoBuf.ProtoMember(21, Name = @"update_effect")]
        public UpdateEffectControlType UpdateEffect
        {
            get => __pbn__ControlType.Is(21) ? ((UpdateEffectControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(21, value);
        }
        public bool ShouldSerializeUpdateEffect() => __pbn__ControlType.Is(21);
        public void ResetUpdateEffect() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 21);

        [global::ProtoBuf.ProtoMember(22, Name = @"begin_scrub")]
        public BeginScrubControlType BeginScrub
        {
            get => __pbn__ControlType.Is(22) ? ((BeginScrubControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(22, value);
        }
        public bool ShouldSerializeBeginScrub() => __pbn__ControlType.Is(22);
        public void ResetBeginScrub() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 22);

        [global::ProtoBuf.ProtoMember(23, Name = @"end_scrub")]
        public EndScrubControlType EndScrub
        {
            get => __pbn__ControlType.Is(23) ? ((EndScrubControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(23, value);
        }
        public bool ShouldSerializeEndScrub() => __pbn__ControlType.Is(23);
        public void ResetEndScrub() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 23);

        [global::ProtoBuf.ProtoMember(24, Name = @"scrub_to_time")]
        public ScrubToTimeControlType ScrubToTime
        {
            get => __pbn__ControlType.Is(24) ? ((ScrubToTimeControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(24, value);
        }
        public bool ShouldSerializeScrubToTime() => __pbn__ControlType.Is(24);
        public void ResetScrubToTime() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 24);

        [global::ProtoBuf.ProtoMember(25, Name = @"scrub_to_percent")]
        public ScrubToPercentControlType ScrubToPercent
        {
            get => __pbn__ControlType.Is(25) ? ((ScrubToPercentControlType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(25, value);
        }
        public bool ShouldSerializeScrubToPercent() => __pbn__ControlType.Is(25);
        public void ResetScrubToPercent() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 25);

        [global::ProtoBuf.ProtoMember(26, Name = @"set_audio_fade")]
        public SetAudioFadeType SetAudioFade
        {
            get => __pbn__ControlType.Is(26) ? ((SetAudioFadeType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(26, value);
        }
        public bool ShouldSerializeSetAudioFade() => __pbn__ControlType.Is(26);
        public void ResetSetAudioFade() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 26);

        [global::ProtoBuf.ProtoMember(27, Name = @"set_audio_properties")]
        public SetAudioPropertiesType SetAudioProperties
        {
            get => __pbn__ControlType.Is(27) ? ((SetAudioPropertiesType)__pbn__ControlType.Object) : default;
            set => __pbn__ControlType = new global::ProtoBuf.DiscriminatedUnionObject(27, value);
        }
        public bool ShouldSerializeSetAudioProperties() => __pbn__ControlType.Is(27);
        public void ResetSetAudioProperties() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ControlType, 27);

        [global::ProtoBuf.ProtoContract()]
        public partial class PlayControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class PauseControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RewindControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class FastForwardControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SkipBackControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"offset")]
            public double Offset { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SkipForwardControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"offset")]
            public double Offset { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class StepBackControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class StepForwardControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class GoToStartControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"offset")]
            public double Offset { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class GoToEndControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"offset")]
            public double Offset { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class JumpToTimeControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"time")]
            public double Time { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class JumpToPercentControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"percent")]
            public double Percent { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class MarkInPointControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"time")]
            public double Time { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class MarkOutPointControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"time")]
            public double Time { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SetScaleModeControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"mode")]
            public ScaleBehavior Mode { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"alignment")]
            public ScaleAlignment Alignment { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum ScaleBehavior
            {
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_FIT")]
                ScaleBehaviorFit = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_FILL")]
                ScaleBehaviorFill = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_STRETCH")]
                ScaleBehaviorStretch = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_BEHAVIOR_CUSTOM")]
                ScaleBehaviorCustom = 3,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum ScaleAlignment
            {
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_MIDDLE_CENTER")]
                ScaleAlignmentMiddleCenter = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_TOP_LEFT")]
                ScaleAlignmentTopLeft = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_TOP_CENTER")]
                ScaleAlignmentTopCenter = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_TOP_RIGHT")]
                ScaleAlignmentTopRight = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_MIDDLE_RIGHT")]
                ScaleAlignmentMiddleRight = 4,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_BOTTOM_RIGHT")]
                ScaleAlignmentBottomRight = 5,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_BOTTOM_CENTER")]
                ScaleAlignmentBottomCenter = 6,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_BOTTOM_LEFT")]
                ScaleAlignmentBottomLeft = 7,
                [global::ProtoBuf.ProtoEnum(Name = @"SCALE_ALIGNMENT_MIDDLE_LEFT")]
                ScaleAlignmentMiddleLeft = 8,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SetFlippedModeControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"horizontal")]
            public bool Horizontal { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"vertical")]
            public bool Vertical { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SetPlayRateControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"play_rate")]
            public double PlayRate { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SetNativeRotationControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"rotation")]
            public NativeRotationType Rotation { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum NativeRotationType
            {
                [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_STANDARD")]
                NativeRotationTypeRotateStandard = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_90")]
                NativeRotationTypeRotate90 = 90,
                [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_180")]
                NativeRotationTypeRotate180 = 180,
                [global::ProtoBuf.ProtoEnum(Name = @"NATIVE_ROTATION_TYPE_ROTATE_270")]
                NativeRotationTypeRotate270 = 270,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class TogglePlaybackControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SetEffectsControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"effects")]
            public global::System.Collections.Generic.List<Effect> Effects { get; } = new global::System.Collections.Generic.List<Effect>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class UpdateEffectControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"effect")]
            public Effect Effect { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class BeginScrubControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EndScrubControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ScrubToTimeControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"time")]
            public double Time { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ScrubToPercentControlType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"percent")]
            public double Percent { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SetAudioFadeType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"fade_in_duration")]
            public double FadeInDuration { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"fade_out_duration")]
            public double FadeOutDuration { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"should_fade_in")]
            public bool ShouldFadeIn { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"should_fade_out")]
            public bool ShouldFadeOut { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class SetAudioPropertiesType : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"audio_properties")]
            public Media.AudioProperties AudioProperties { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"solo", IsPacked = true)]
            public bool[] Soloes { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AudioInputSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"inputs")]
        public global::System.Collections.Generic.List<AudioInput> Inputs { get; } = new global::System.Collections.Generic.List<AudioInput>();

        [global::ProtoBuf.ProtoMember(2)]
        public double transitionTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VideoInputSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"inputs")]
        public global::System.Collections.Generic.List<VideoInput> Inputs { get; } = new global::System.Collections.Generic.List<VideoInput>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RecordRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stream")]
        public Recording.Stream Stream { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"working_directory")]
        public Url WorkingDirectory { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Resi resi { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Resi : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"gop")]
            public uint Gop { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public double segmentSize { get; set; }

            [global::ProtoBuf.ProtoMember(3)]
            [global::System.ComponentModel.DefaultValue("")]
            public string destinationGroupId { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4)]
            public uint bufSize { get; set; }

            [global::ProtoBuf.ProtoMember(5)]
            public uint minRate { get; set; }

            [global::ProtoBuf.ProtoMember(6)]
            public uint maxRate { get; set; }

            [global::ProtoBuf.ProtoMember(7)]
            [global::System.ComponentModel.DefaultValue("")]
            public string eventName { get; set; } = "";

            [global::ProtoBuf.ProtoMember(8, Name = @"social_description")]
            [global::System.ComponentModel.DefaultValue("")]
            public string SocialDescription { get; set; } = "";

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextSegmentRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"segments")]
        public global::System.Collections.Generic.List<Segment> Segments { get; } = new global::System.Collections.Generic.List<Segment>();

        [global::ProtoBuf.ProtoMember(2, Name = @"start_position")]
        public double StartPosition { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Segment : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"index")]
            public uint Index { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"size")]
            public double Size { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProClockSource : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uuid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"connected")]
        public bool Connected { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"active")]
        public bool Active { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_UNKOWN")]
            TypeUnkown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_INPUT")]
            TypeInput = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_OUTPUT")]
            TypeOutput = 2,
        }

    }

}


#endregion
