// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: propresenter.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlaylistDocument : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"application_info")]
        public ApplicationInfo ApplicationInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"root_node")]
        public Playlist RootNode { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"tags")]
        public global::System.Collections.Generic.List<Playlist.Tag> Tags { get; } = new global::System.Collections.Generic.List<Playlist.Tag>();

        [global::ProtoBuf.ProtoMember(5, Name = @"live_video_playlist")]
        public Playlist LiveVideoPlaylist { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"downloads_playlist")]
        public Playlist DownloadsPlaylist { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_UNKNOWN")]
            TypeUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_PRESENTATION")]
            TypePresentation = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_MEDIA")]
            TypeMedia = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_AUDIO")]
            TypeAudio = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SettingsDocument : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"labels")]
        public global::System.Collections.Generic.List<Action.Label> Labels { get; } = new global::System.Collections.Generic.List<Action.Label>();

    }

}


#endregion
