// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: proscreen.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ProPresenterScreen : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public ScreenType screen_type { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"background_color")]
        public Color BackgroundColor { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"background_color_enabled")]
        public bool BackgroundColorEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"arrangement_single")]
        public SingleArrangement ArrangementSingle
        {
            get => __pbn__Arrangement.Is(3) ? ((SingleArrangement)__pbn__Arrangement.Object) : default;
            set => __pbn__Arrangement = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeArrangementSingle() => __pbn__Arrangement.Is(3);
        public void ResetArrangementSingle() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Arrangement, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__Arrangement;

        [global::ProtoBuf.ProtoMember(4, Name = @"arrangement_combined")]
        public CombinedArrangement ArrangementCombined
        {
            get => __pbn__Arrangement.Is(4) ? ((CombinedArrangement)__pbn__Arrangement.Object) : default;
            set => __pbn__Arrangement = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeArrangementCombined() => __pbn__Arrangement.Is(4);
        public void ResetArrangementCombined() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Arrangement, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"arrangement_edge_blend")]
        public EdgeBlendArrangement ArrangementEdgeBlend
        {
            get => __pbn__Arrangement.Is(5) ? ((EdgeBlendArrangement)__pbn__Arrangement.Object) : default;
            set => __pbn__Arrangement = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeArrangementEdgeBlend() => __pbn__Arrangement.Is(5);
        public void ResetArrangementEdgeBlend() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Arrangement, 5);

        [global::ProtoBuf.ProtoContract()]
        public partial class SingleArrangement : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"screens")]
            public global::System.Collections.Generic.List<Screen> Screens { get; } = new global::System.Collections.Generic.List<Screen>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class CombinedArrangement : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"screens")]
            public global::System.Collections.Generic.List<Screen> Screens { get; } = new global::System.Collections.Generic.List<Screen>();

            [global::ProtoBuf.ProtoMember(2, Name = @"rows")]
            public uint Rows { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"columns")]
            public uint Columns { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class EdgeBlendArrangement : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"screen_count")]
            public uint ScreenCount { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"screens")]
            public global::System.Collections.Generic.List<Screen> Screens { get; } = new global::System.Collections.Generic.List<Screen>();

            [global::ProtoBuf.ProtoMember(3, Name = @"edge_blends")]
            public global::System.Collections.Generic.List<EdgeBlend> EdgeBlends { get; } = new global::System.Collections.Generic.List<EdgeBlend>();

        }

        [global::ProtoBuf.ProtoContract()]
        public enum ScreenType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SCREEN_TYPE_UNKNOWN")]
            ScreenTypeUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SCREEN_TYPE_AUDIENCE")]
            ScreenTypeAudience = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SCREEN_TYPE_STAGE")]
            ScreenTypeStage = 2,
        }

    }

}


#endregion
