// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: proworkspace.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ProPresenterWorkspace : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pro_screens")]
        public global::System.Collections.Generic.List<ProPresenterScreen> ProScreens { get; } = new global::System.Collections.Generic.List<ProPresenterScreen>();

        [global::ProtoBuf.ProtoMember(2, Name = @"audience_looks")]
        public global::System.Collections.Generic.List<ProAudienceLook> AudienceLooks { get; } = new global::System.Collections.Generic.List<ProAudienceLook>();

        [global::ProtoBuf.ProtoMember(3, Name = @"live_audience_look")]
        public ProAudienceLook LiveAudienceLook { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"masks")]
        public global::System.Collections.Generic.List<ProMask> Masks { get; } = new global::System.Collections.Generic.List<ProMask>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<VideoInput> videoInputs { get; } = new global::System.Collections.Generic.List<VideoInput>();

        [global::ProtoBuf.ProtoMember(6, Name = @"stage_layout_mappings")]
        public global::System.Collections.Generic.List<Stage.ScreenAssignment> StageLayoutMappings { get; } = new global::System.Collections.Generic.List<Stage.ScreenAssignment>();

        [global::ProtoBuf.ProtoMember(7, Name = @"audio_settings")]
        public Audio.SettingsDocument AudioSettings { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"selected_library_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SelectedLibraryName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"record_settings")]
        public Recording.SettingsDocument RecordSettings { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"digital_audio_setup")]
        public DigitalAudio.Setup DigitalAudioSetup { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"audio_inputs")]
        public global::System.Collections.Generic.List<AudioInput> AudioInputs { get; } = new global::System.Collections.Generic.List<AudioInput>();

        [global::ProtoBuf.ProtoMember(12, Name = @"audio_input_transition_time")]
        public double AudioInputTransitionTime { get; set; }

    }

}


#endregion
