// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: recording.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Recording : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoContract()]
        public partial class SettingsDocument : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"streams")]
            public global::System.Collections.Generic.List<Recording.Stream> Streams { get; } = new global::System.Collections.Generic.List<Recording.Stream>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Stream : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"id")]
            public Uuid Id { get; set; }

            [global::ProtoBuf.ProtoMember(3)]
            public Encoder encoder { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"destinations")]
            public global::System.Collections.Generic.List<Destination> Destinations { get; } = new global::System.Collections.Generic.List<Destination>();

            [global::ProtoBuf.ProtoMember(5, Name = @"audio_map")]
            public global::System.Collections.Generic.List<DigitalAudio.Device.Map> AudioMaps { get; } = new global::System.Collections.Generic.List<DigitalAudio.Device.Map>();

            [global::ProtoBuf.ProtoMember(6)]
            public bool isAudioCustomMapped { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"output_screen")]
            public OutputScreenSource OutputScreen { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public partial class Encoder : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1)]
                public Codec codec { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"video_width")]
                public uint VideoWidth { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"video_height")]
                public uint VideoHeight { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"is_interlaced")]
                public bool IsInterlaced { get; set; }

                [global::ProtoBuf.ProtoMember(5)]
                public FrameRate frameRate { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"video_bitrate")]
                public uint VideoBitrate { get; set; }

                [global::ProtoBuf.ProtoContract()]
                public enum Codec
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_AUTOMATIC")]
                    CodecAutomatic = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_H264")]
                    CodecH264 = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_H265")]
                    CodecH265 = 2,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_PRORES_422_PROXY")]
                    CodecProres422Proxy = 3,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_PRORES_422_LT")]
                    CodecProres422Lt = 4,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_PRORES_422")]
                    CodecProres422 = 5,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_PRORES_422_HQ")]
                    CodecProres422Hq = 6,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_PRORES_4444")]
                    CodecProres4444 = 7,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_PRORES_4444_XQ")]
                    CodecProres4444Xq = 8,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_HAP")]
                    CodecHap = 9,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_HAP_ALPHA")]
                    CodecHapAlpha = 10,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_HAP_Q")]
                    CodecHapQ = 11,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_HAP_Q_ALPHA")]
                    CodecHapQAlpha = 12,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_NOTCH")]
                    CodecNotch = 13,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_H264_SOFTWARE")]
                    CodecH264Software = 14,
                    [global::ProtoBuf.ProtoEnum(Name = @"CODEC_H265_SOFTWARE")]
                    CodecH265Software = 15,
                }

                [global::ProtoBuf.ProtoContract()]
                public enum FrameRate
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"FRAME_RATE_UNKNOWN")]
                    FrameRateUnknown = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"FRAME_RATE_24")]
                    FrameRate24 = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"FRAME_RATE_25")]
                    FrameRate25 = 2,
                    [global::ProtoBuf.ProtoEnum(Name = @"FRAME_RATE_29_97")]
                    FrameRate2997 = 3,
                    [global::ProtoBuf.ProtoEnum(Name = @"FRAME_RATE_30")]
                    FrameRate30 = 4,
                    [global::ProtoBuf.ProtoEnum(Name = @"FRAME_RATE_50")]
                    FrameRate50 = 5,
                    [global::ProtoBuf.ProtoEnum(Name = @"FRAME_RATE_59_94")]
                    FrameRate5994 = 6,
                    [global::ProtoBuf.ProtoEnum(Name = @"FRAME_RATE_60")]
                    FrameRate60 = 7,
                }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class OutputScreenSource : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"screen_id")]
                public Uuid ScreenId { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"screen_name")]
                [global::System.ComponentModel.DefaultValue("")]
                public string ScreenName { get; set; } = "";

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class DiskDestination : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"location")]
                public Url Location { get; set; }

                [global::ProtoBuf.ProtoMember(2)]
                public Container container { get; set; }

                [global::ProtoBuf.ProtoContract()]
                public enum Container
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"CONTAINER_UNKNOWN")]
                    ContainerUnknown = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"CONTAINER_MOV")]
                    ContainerMov = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"CONTAINER_MP4")]
                    ContainerMp4 = 2,
                }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class RTMPDestination : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"address")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Address { get; set; } = "";

                [global::ProtoBuf.ProtoMember(2, Name = @"key")]
                [global::System.ComponentModel.DefaultValue("")]
                public string Key { get; set; } = "";

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class Destination : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"disk")]
                public Recording.Stream.DiskDestination Disk
                {
                    get => __pbn__Destination.Is(1) ? ((Recording.Stream.DiskDestination)__pbn__Destination.Object) : default;
                    set => __pbn__Destination = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
                }
                public bool ShouldSerializeDisk() => __pbn__Destination.Is(1);
                public void ResetDisk() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Destination, 1);

                private global::ProtoBuf.DiscriminatedUnionObject __pbn__Destination;

                [global::ProtoBuf.ProtoMember(2, Name = @"rtmp")]
                public Recording.Stream.RTMPDestination Rtmp
                {
                    get => __pbn__Destination.Is(2) ? ((Recording.Stream.RTMPDestination)__pbn__Destination.Object) : default;
                    set => __pbn__Destination = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
                }
                public bool ShouldSerializeRtmp() => __pbn__Destination.Is(2);
                public void ResetRtmp() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Destination, 2);

                [global::ProtoBuf.ProtoMember(3)]
                public Resi resi
                {
                    get => __pbn__Destination.Is(3) ? ((Resi)__pbn__Destination.Object) : default;
                    set => __pbn__Destination = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
                }
                public bool ShouldSerializeresi() => __pbn__Destination.Is(3);
                public void Resetresi() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__Destination, 3);

                [global::ProtoBuf.ProtoContract()]
                public partial class Resi : global::ProtoBuf.IExtensible
                {
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"destination_group_id")]
                    public Uuid DestinationGroupId { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"encoder_profile_id")]
                    public Uuid EncoderProfileId { get; set; }

                }

            }

        }

    }

}


#endregion
