// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: screens.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Screen : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"color")]
        public Color Color { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"bounds")]
        public Graphics.Rect Bounds { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"aspect_ratio_locked")]
        public bool AspectRatioLocked { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"output_bounds_aspect_ratio_locked")]
        public bool OutputBoundsAspectRatioLocked { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"corner_pinning_enabled")]
        public bool CornerPinningEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"subscreen_unit_rect")]
        public Graphics.Rect SubscreenUnitRect { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"rotation")]
        public double Rotation { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"gamma")]
        public double Gamma { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"black_level")]
        public double BlackLevel { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"blended_edges")]
        public uint BlendedEdges { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"corner_values")]
        public CornerValues CornerValues { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"output_display")]
        public OutputDisplay OutputDisplay { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"color_enabled")]
        public bool ColorEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public ColorAdjustment color_adjustment { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public BlendCompensation blend_compensation { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class ColorAdjustment : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"gamma")]
            public double Gamma { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"black_level")]
            public double BlackLevel { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"red_level")]
            public double RedLevel { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"green_level")]
            public double GreenLevel { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"blue_level")]
            public double BlueLevel { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"brightness")]
            public double Brightness { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"contrast")]
            public double Contrast { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class BlendCompensation : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"black_level")]
            public double BlackLevel { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CornerValues : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"top_left")]
        public Graphics.Point TopLeft { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"top_right")]
        public Graphics.Point TopRight { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"bottom_left")]
        public Graphics.Point BottomLeft { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"bottom_right")]
        public Graphics.Point BottomRight { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DisplayMode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"width")]
        public uint Width { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"height")]
        public uint Height { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"refresh_rate")]
        public double RefreshRate { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"interlaced")]
        public bool Interlaced { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OutputDisplay : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"model")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Model { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"serial")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Serial { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string deviceName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"vendor")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Vendor { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public uint modeIndex { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"bounds")]
        public Graphics.Rect Bounds { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"mode")]
        public DisplayMode Mode { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"render_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RenderId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"black_magic_alpha_key_settings")]
        public BlackmagicAlphaKeySettings BlackMagicAlphaKeySettings { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class BlackmagicAlphaKeySettings : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"enabled")]
            public bool Enabled { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public KeyMode key_mode { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"blend_value")]
            public double BlendValue { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum KeyMode
            {
                [global::ProtoBuf.ProtoEnum(Name = @"KEY_MODE_INTERNAL")]
                KeyModeInternal = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"KEY_MODE_EXTERNAL")]
                KeyModeExternal = 1,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_UNKNOWN")]
            TypeUnknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_SCREEN")]
            TypeScreen = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_CARD")]
            TypeCard = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_NDI")]
            TypeNdi = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_SYPHON")]
            TypeSyphon = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_CUSTOM")]
            TypeCustom = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EdgeBlend : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"radius")]
        public double Radius { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"intensity")]
        public double Intensity { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Mode mode { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"first_screen")]
        public Screen FirstScreen { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"second_screen")]
        public Screen SecondScreen { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"left_screen")]
        public Screen LeftScreen { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"right_screen")]
        public Screen RightScreen { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"top_screen")]
        public Screen TopScreen { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"bottom_screen")]
        public Screen BottomScreen { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Screen : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
            public Uuid Uuid { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public Edge edge { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"gamma")]
            public double Gamma { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"black_level")]
            public double BlackLevel { get; set; }

            [global::ProtoBuf.ProtoMember(5)]
            public Mode mode { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"radius")]
            public double Radius { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"intensity")]
            public double Intensity { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum Edge
            {
                [global::ProtoBuf.ProtoEnum(Name = @"EDGE_UNKNOWN")]
                EdgeUnknown = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"EDGE_LEFT")]
                EdgeLeft = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"EDGE_RIGHT")]
                EdgeRight = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"EDGE_TOP")]
                EdgeTop = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"EDGE_BOTTOM")]
                EdgeBottom = 4,
            }

            [global::ProtoBuf.ProtoContract()]
            public enum Mode
            {
                [global::ProtoBuf.ProtoEnum(Name = @"MODE_LINEAR")]
                ModeLinear = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"MODE_CUBIC")]
                ModeCubic = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"MODE_QUADRATIC")]
                ModeQuadratic = 2,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Mode
        {
            [global::ProtoBuf.ProtoEnum(Name = @"MODE_LINEAR")]
            ModeLinear = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"MODE_CUBIC")]
            ModeCubic = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MODE_QUADRATIC")]
            ModeQuadratic = 2,
        }

    }

}


#endregion
