// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: timers.proto
// </auto-generated>

#region Designer generated code

namespace rv.data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Clock : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string format { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public partial class Format : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(2, Name = @"date_type")]
            public DateFormatterStyle DateType { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"time_format")]
            public DateFormatterStyle TimeFormat { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"military_time_enabled")]
            public bool MilitaryTimeEnabled { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum DateFormatterStyle
            {
                [global::ProtoBuf.ProtoEnum(Name = @"DATE_FORMATTER_STYLE_NONE")]
                DateFormatterStyleNone = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"DATE_FORMATTER_STYLE_SHORT")]
                DateFormatterStyleShort = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"DATE_FORMATTER_STYLE_MEDIUM")]
                DateFormatterStyleMedium = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"DATE_FORMATTER_STYLE_LONG")]
                DateFormatterStyleLong = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"DATE_FORMATTER_STYLE_FULL")]
                DateFormatterStyleFull = 4,
            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Timer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public Uuid Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10)]
        public Configuration configuration { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Format : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"hour")]
            public Style Hour { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"minute")]
            public Style Minute { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"second")]
            public Style Second { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"millisecond")]
            public Style Millisecond { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"is_wall_clock_time")]
            public bool IsWallClockTime { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"is_24_hour_time")]
            public bool Is24HourTime { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"show_milliseconds_under_minute_only")]
            public bool ShowMillisecondsUnderMinuteOnly { get; set; }

            [global::ProtoBuf.ProtoContract()]
            public enum Style
            {
                [global::ProtoBuf.ProtoEnum(Name = @"STYE_NONE")]
                StyeNone = 0,
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_SHORT")]
                StyleShort = 1,
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_LONG")]
                StyleLong = 2,
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_REMOVE_SHORT")]
                StyleRemoveShort = 3,
                [global::ProtoBuf.ProtoEnum(Name = @"STYLE_REMOVE_LONG")]
                StyleRemoveLong = 4,
            }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Configuration : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(4, Name = @"allows_overrun")]
            public bool AllowsOverrun { get; set; }

            [global::ProtoBuf.ProtoMember(1, Name = @"countdown")]
            public TimerTypeCountdown Countdown
            {
                get => __pbn__TimerType.Is(1) ? ((TimerTypeCountdown)__pbn__TimerType.Object) : default;
                set => __pbn__TimerType = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
            }
            public bool ShouldSerializeCountdown() => __pbn__TimerType.Is(1);
            public void ResetCountdown() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TimerType, 1);

            private global::ProtoBuf.DiscriminatedUnionObject __pbn__TimerType;

            [global::ProtoBuf.ProtoMember(2, Name = @"countdown_to_time")]
            public TimerTypeCountdownToTime CountdownToTime
            {
                get => __pbn__TimerType.Is(2) ? ((TimerTypeCountdownToTime)__pbn__TimerType.Object) : default;
                set => __pbn__TimerType = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
            }
            public bool ShouldSerializeCountdownToTime() => __pbn__TimerType.Is(2);
            public void ResetCountdownToTime() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TimerType, 2);

            [global::ProtoBuf.ProtoMember(3, Name = @"elapsed_time")]
            public TimerTypeElapsedTime ElapsedTime
            {
                get => __pbn__TimerType.Is(3) ? ((TimerTypeElapsedTime)__pbn__TimerType.Object) : default;
                set => __pbn__TimerType = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
            }
            public bool ShouldSerializeElapsedTime() => __pbn__TimerType.Is(3);
            public void ResetElapsedTime() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__TimerType, 3);

            [global::ProtoBuf.ProtoContract()]
            public partial class TimerTypeCountdown : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"duration")]
                public double Duration { get; set; }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class TimerTypeCountdownToTime : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"time_of_day")]
                public double TimeOfDay { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"period")]
                public TimePeriod Period { get; set; }

                [global::ProtoBuf.ProtoContract()]
                public enum TimePeriod
                {
                    [global::ProtoBuf.ProtoEnum(Name = @"TIME_PERIOD_AM")]
                    TimePeriodAm = 0,
                    [global::ProtoBuf.ProtoEnum(Name = @"TIME_PERIOD_PM")]
                    TimePeriodPm = 1,
                    [global::ProtoBuf.ProtoEnum(Name = @"TIME_PERIOD_24")]
                    TimePeriod24 = 2,
                }

            }

            [global::ProtoBuf.ProtoContract()]
            public partial class TimerTypeElapsedTime : global::ProtoBuf.IExtensible
            {
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"start_time")]
                public double StartTime { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"end_time")]
                public double EndTime { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"has_end_time")]
                public bool HasEndTime { get; set; }

            }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TimersDocument : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"application_info")]
        public ApplicationInfo ApplicationInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"clock")]
        public Clock Clock { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"timers")]
        public global::System.Collections.Generic.List<Timer> Timers { get; } = new global::System.Collections.Generic.List<Timer>();

    }

}


#endregion
